package com.kyee.mapper;

import com.kyee.model.VHisLabResultInfo;
import java.util.List;

public interface VHisLabResultInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_RESULT_INFO
     *
     * @mbggenerated
     */
    int insert(VHisLabResultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_RESULT_INFO
     *
     * @mbggenerated
     */
    List<VHisLabResultInfo> selectAll();
}