package com.kyee.mapper;

import com.kyee.model.VHisDischargeSummary;
import java.util.List;

public interface VHisDischargeSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DISCHARGE_SUMMARY
     *
     * @mbggenerated
     */
    int insert(VHisDischargeSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DISCHARGE_SUMMARY
     *
     * @mbggenerated
     */
    List<VHisDischargeSummary> selectAll();
}