package com.kyee.mapper;

import com.kyee.model.VHisLabInfo;
import java.util.List;

public interface VHisLabInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String testNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_INFO
     *
     * @mbggenerated
     */
    int insert(VHisLabInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_INFO
     *
     * @mbggenerated
     */
    VHisLabInfo selectByPrimaryKey(String testNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_INFO
     *
     * @mbggenerated
     */
    List<VHisLabInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_LAB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisLabInfo record);
}