package com.kyee.mapper;

import com.kyee.model.VHisClinicDiagnosisInfo;
import java.util.List;

public interface VHisClinicDiagnosisInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_CLINIC_DIAGNOSIS_INFO
     *
     * @mbggenerated
     */
    int insert(VHisClinicDiagnosisInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_CLINIC_DIAGNOSIS_INFO
     *
     * @mbggenerated
     */
    List<VHisClinicDiagnosisInfo> selectAll();
}