package com.kyee.mapper;

import com.kyee.model.VHisPhysicalDetailed;
import java.util.List;

public interface VHisPhysicalDetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_DETAILED
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String physicalDetailedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_DETAILED
     *
     * @mbggenerated
     */
    int insert(VHisPhysicalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_DETAILED
     *
     * @mbggenerated
     */
    VHisPhysicalDetailed selectByPrimaryKey(String physicalDetailedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_DETAILED
     *
     * @mbggenerated
     */
    List<VHisPhysicalDetailed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_DETAILED
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisPhysicalDetailed record);
}