package com.kyee.mapper;

import com.kyee.model.VHisUserDeptRel;
import java.util.List;

public interface VHisUserDeptRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_USER_DEPT_REL
     *
     * @mbggenerated
     */
    int insert(VHisUserDeptRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_USER_DEPT_REL
     *
     * @mbggenerated
     */
    List<VHisUserDeptRel> selectAll();
}