package com.kyee.mapper;

import com.kyee.model.VHisPatientInfo;
import java.util.List;

public interface VHisPatientInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PATIENT_INFO
     *
     * @mbggenerated
     */
    int insert(VHisPatientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PATIENT_INFO
     *
     * @mbggenerated
     */
    List<VHisPatientInfo> selectAll();
}