package com.kyee.mapper;

import com.kyee.model.VHisClinicPatientInfo;
import java.util.List;

public interface VHisClinicPatientInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_CLINIC_PATIENT_INFO
     *
     * @mbggenerated
     */
    int insert(VHisClinicPatientInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_CLINIC_PATIENT_INFO
     *
     * @mbggenerated
     */
    List<VHisClinicPatientInfo> selectAll();
}