package com.kyee.mapper;

import com.kyee.model.VHisOperationDetail;
import java.util.List;

public interface VHisOperationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_OPERATION_DETAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String operationDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_OPERATION_DETAIL
     *
     * @mbggenerated
     */
    int insert(VHisOperationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_OPERATION_DETAIL
     *
     * @mbggenerated
     */
    VHisOperationDetail selectByPrimaryKey(String operationDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_OPERATION_DETAIL
     *
     * @mbggenerated
     */
    List<VHisOperationDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_OPERATION_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisOperationDetail record);
}