package com.kyee.mapper;

import com.kyee.model.VHisDiagnosisInfo;
import java.util.List;

public interface VHisDiagnosisInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DIAGNOSIS_INFO
     *
     * @mbggenerated
     */
    int insert(VHisDiagnosisInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DIAGNOSIS_INFO
     *
     * @mbggenerated
     */
    List<VHisDiagnosisInfo> selectAll();
}