package com.kyee.mapper;

import com.kyee.model.VHisPhysicalInfo;
import java.util.List;

public interface VHisPhysicalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String physicalNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_INFO
     *
     * @mbggenerated
     */
    int insert(VHisPhysicalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_INFO
     *
     * @mbggenerated
     */
    VHisPhysicalInfo selectByPrimaryKey(String physicalNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_INFO
     *
     * @mbggenerated
     */
    List<VHisPhysicalInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisPhysicalInfo record);
}