package com.kyee.mapper;

import com.kyee.model.VHisExamResultInfo;
import java.util.List;

public interface VHisExamResultInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_EXAM_RESULT_INFO
     *
     * @mbggenerated
     */
    int insert(VHisExamResultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_EXAM_RESULT_INFO
     *
     * @mbggenerated
     */
    List<VHisExamResultInfo> selectAll();
}