package com.kyee.mapper;

import com.kyee.model.VHisDeptInfo;
import java.util.List;
import java.util.Map;

public interface VHisDeptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DEPT_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String deptCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DEPT_INFO
     *
     * @mbggenerated
     */
    int insert(VHisDeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DEPT_INFO
     *
     * @mbggenerated
     */
    VHisDeptInfo selectByPrimaryKey(String deptCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DEPT_INFO
     *
     * @mbggenerated
     */
    List<Map<String,Object>> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_DEPT_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisDeptInfo record);
}