package com.kyee.mapper;

import com.kyee.model.VHisPhysicalSummary;
import java.util.List;

public interface VHisPhysicalSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String physicalSummaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    int insert(VHisPhysicalSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    VHisPhysicalSummary selectByPrimaryKey(String physicalSummaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    List<VHisPhysicalSummary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_HIS_PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VHisPhysicalSummary record);
}