package com.kyee.model;

import java.util.Date;

public class VHisPhysicalDetailed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_ID
     *
     * @mbggenerated
     */
    private String physicalDetailedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    private String physicalSummaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    private String physicalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    private String itemClassCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    private String itemClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.ITEM_CODE
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.RESULT
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    private String referenceRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.ABNORMAL
     *
     * @mbggenerated
     */
    private String abnormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_TIME
     *
     * @mbggenerated
     */
    private Date physicalDetailedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_ID
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_ID
     *
     * @mbggenerated
     */
    public String getPhysicalDetailedId() {
        return physicalDetailedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_ID
     *
     * @param physicalDetailedId the value for V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_ID
     *
     * @mbggenerated
     */
    public void setPhysicalDetailedId(String physicalDetailedId) {
        this.physicalDetailedId = physicalDetailedId == null ? null : physicalDetailedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_SUMMARY_ID
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    public String getPhysicalSummaryId() {
        return physicalSummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_SUMMARY_ID
     *
     * @param physicalSummaryId the value for V_HIS_PHYSICAL_DETAILED.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    public void setPhysicalSummaryId(String physicalSummaryId) {
        this.physicalSummaryId = physicalSummaryId == null ? null : physicalSummaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_NUMBER
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public String getPhysicalNumber() {
        return physicalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_NUMBER
     *
     * @param physicalNumber the value for V_HIS_PHYSICAL_DETAILED.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public void setPhysicalNumber(String physicalNumber) {
        this.physicalNumber = physicalNumber == null ? null : physicalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_CODE
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    public String getItemClassCode() {
        return itemClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_CODE
     *
     * @param itemClassCode the value for V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    public void setItemClassCode(String itemClassCode) {
        this.itemClassCode = itemClassCode == null ? null : itemClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_NAME
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    public String getItemClassName() {
        return itemClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_NAME
     *
     * @param itemClassName the value for V_HIS_PHYSICAL_DETAILED.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    public void setItemClassName(String itemClassName) {
        this.itemClassName = itemClassName == null ? null : itemClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CODE
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.ITEM_CODE
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_CODE
     *
     * @param itemCode the value for V_HIS_PHYSICAL_DETAILED.ITEM_CODE
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_NAME
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.ITEM_NAME
     *
     * @param itemName the value for V_HIS_PHYSICAL_DETAILED.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.RESULT
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.RESULT
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.RESULT
     *
     * @param result the value for V_HIS_PHYSICAL_DETAILED.RESULT
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.UNIT
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.UNIT
     *
     * @param unit the value for V_HIS_PHYSICAL_DETAILED.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.REFERENCE_RANGE
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    public String getReferenceRange() {
        return referenceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.REFERENCE_RANGE
     *
     * @param referenceRange the value for V_HIS_PHYSICAL_DETAILED.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    public void setReferenceRange(String referenceRange) {
        this.referenceRange = referenceRange == null ? null : referenceRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.ABNORMAL
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.ABNORMAL
     *
     * @mbggenerated
     */
    public String getAbnormal() {
        return abnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.ABNORMAL
     *
     * @param abnormal the value for V_HIS_PHYSICAL_DETAILED.ABNORMAL
     *
     * @mbggenerated
     */
    public void setAbnormal(String abnormal) {
        this.abnormal = abnormal == null ? null : abnormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_TIME
     *
     * @return the value of V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_TIME
     *
     * @mbggenerated
     */
    public Date getPhysicalDetailedTime() {
        return physicalDetailedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_TIME
     *
     * @param physicalDetailedTime the value for V_HIS_PHYSICAL_DETAILED.PHYSICAL_DETAILED_TIME
     *
     * @mbggenerated
     */
    public void setPhysicalDetailedTime(Date physicalDetailedTime) {
        this.physicalDetailedTime = physicalDetailedTime;
    }
}