package com.kyee.model;

import java.util.Date;

public class VHisMedication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.MEDICATION_ID
     *
     * @mbggenerated
     */
    private String medicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    private String patientSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.IS_STRUCTURING
     *
     * @mbggenerated
     */
    private String isStructuring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.DRUG_NAME
     *
     * @mbggenerated
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.DRUG_UNITS
     *
     * @mbggenerated
     */
    private String drugUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.DRUG_USAGE
     *
     * @mbggenerated
     */
    private String drugUsage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.DRUG_DOSAGE
     *
     * @mbggenerated
     */
    private String drugDosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.MEDICATION_DATE
     *
     * @mbggenerated
     */
    private Date medicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_MEDICATION.MEDICATION_TEXT
     *
     * @mbggenerated
     */
    private String medicationText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.MEDICATION_ID
     *
     * @return the value of V_HIS_MEDICATION.MEDICATION_ID
     *
     * @mbggenerated
     */
    public String getMedicationId() {
        return medicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.MEDICATION_ID
     *
     * @param medicationId the value for V_HIS_MEDICATION.MEDICATION_ID
     *
     * @mbggenerated
     */
    public void setMedicationId(String medicationId) {
        this.medicationId = medicationId == null ? null : medicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.PATIENT_ID
     *
     * @return the value of V_HIS_MEDICATION.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.PATIENT_ID
     *
     * @param patientId the value for V_HIS_MEDICATION.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.VISIT_NO
     *
     * @return the value of V_HIS_MEDICATION.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.VISIT_NO
     *
     * @param visitNo the value for V_HIS_MEDICATION.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.INHOSPITAL_NO
     *
     * @return the value of V_HIS_MEDICATION.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_MEDICATION.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.OUTPATIENT_NO
     *
     * @return the value of V_HIS_MEDICATION.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_MEDICATION.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.PATIENT_SOURCE
     *
     * @return the value of V_HIS_MEDICATION.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public String getPatientSource() {
        return patientSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.PATIENT_SOURCE
     *
     * @param patientSource the value for V_HIS_MEDICATION.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public void setPatientSource(String patientSource) {
        this.patientSource = patientSource == null ? null : patientSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.IS_STRUCTURING
     *
     * @return the value of V_HIS_MEDICATION.IS_STRUCTURING
     *
     * @mbggenerated
     */
    public String getIsStructuring() {
        return isStructuring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.IS_STRUCTURING
     *
     * @param isStructuring the value for V_HIS_MEDICATION.IS_STRUCTURING
     *
     * @mbggenerated
     */
    public void setIsStructuring(String isStructuring) {
        this.isStructuring = isStructuring == null ? null : isStructuring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.DRUG_NAME
     *
     * @return the value of V_HIS_MEDICATION.DRUG_NAME
     *
     * @mbggenerated
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.DRUG_NAME
     *
     * @param drugName the value for V_HIS_MEDICATION.DRUG_NAME
     *
     * @mbggenerated
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.DRUG_UNITS
     *
     * @return the value of V_HIS_MEDICATION.DRUG_UNITS
     *
     * @mbggenerated
     */
    public String getDrugUnits() {
        return drugUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.DRUG_UNITS
     *
     * @param drugUnits the value for V_HIS_MEDICATION.DRUG_UNITS
     *
     * @mbggenerated
     */
    public void setDrugUnits(String drugUnits) {
        this.drugUnits = drugUnits == null ? null : drugUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.DRUG_USAGE
     *
     * @return the value of V_HIS_MEDICATION.DRUG_USAGE
     *
     * @mbggenerated
     */
    public String getDrugUsage() {
        return drugUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.DRUG_USAGE
     *
     * @param drugUsage the value for V_HIS_MEDICATION.DRUG_USAGE
     *
     * @mbggenerated
     */
    public void setDrugUsage(String drugUsage) {
        this.drugUsage = drugUsage == null ? null : drugUsage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.DRUG_DOSAGE
     *
     * @return the value of V_HIS_MEDICATION.DRUG_DOSAGE
     *
     * @mbggenerated
     */
    public String getDrugDosage() {
        return drugDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.DRUG_DOSAGE
     *
     * @param drugDosage the value for V_HIS_MEDICATION.DRUG_DOSAGE
     *
     * @mbggenerated
     */
    public void setDrugDosage(String drugDosage) {
        this.drugDosage = drugDosage == null ? null : drugDosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.MEDICATION_DATE
     *
     * @return the value of V_HIS_MEDICATION.MEDICATION_DATE
     *
     * @mbggenerated
     */
    public Date getMedicationDate() {
        return medicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.MEDICATION_DATE
     *
     * @param medicationDate the value for V_HIS_MEDICATION.MEDICATION_DATE
     *
     * @mbggenerated
     */
    public void setMedicationDate(Date medicationDate) {
        this.medicationDate = medicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_MEDICATION.MEDICATION_TEXT
     *
     * @return the value of V_HIS_MEDICATION.MEDICATION_TEXT
     *
     * @mbggenerated
     */
    public String getMedicationText() {
        return medicationText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_MEDICATION.MEDICATION_TEXT
     *
     * @param medicationText the value for V_HIS_MEDICATION.MEDICATION_TEXT
     *
     * @mbggenerated
     */
    public void setMedicationText(String medicationText) {
        this.medicationText = medicationText == null ? null : medicationText.trim();
    }
}