package com.kyee.model;

import java.util.Date;

public class VHisDiagnosisInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    private String icdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.SICK_NAME
     *
     * @mbggenerated
     */
    private String sickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_TYPE_NAME
     *
     * @mbggenerated
     */
    private String diagnosisTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    private String diagnosisOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DESC
     *
     * @mbggenerated
     */
    private String diagnosisDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    private Date diagnosisDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.TREAT_DAYS
     *
     * @mbggenerated
     */
    private String treatDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.TREAT_RESULT
     *
     * @mbggenerated
     */
    private String treatResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DIAGNOSIS_INFO.OPER_TREAT_INDICATOR
     *
     * @mbggenerated
     */
    private String operTreatIndicator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @param patientId the value for V_HIS_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.VISIT_NO
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.VISIT_NO
     *
     * @param visitNo the value for V_HIS_DIAGNOSIS_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.INHOSPITAL_NO
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_DIAGNOSIS_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.ICD_CODE
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    public String getIcdCode() {
        return icdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.ICD_CODE
     *
     * @param icdCode the value for V_HIS_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    public void setIcdCode(String icdCode) {
        this.icdCode = icdCode == null ? null : icdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.SICK_NAME
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.SICK_NAME
     *
     * @mbggenerated
     */
    public String getSickName() {
        return sickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.SICK_NAME
     *
     * @param sickName the value for V_HIS_DIAGNOSIS_INFO.SICK_NAME
     *
     * @mbggenerated
     */
    public void setSickName(String sickName) {
        this.sickName = sickName == null ? null : sickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_TYPE_NAME
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getDiagnosisTypeName() {
        return diagnosisTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_TYPE_NAME
     *
     * @param diagnosisTypeName the value for V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setDiagnosisTypeName(String diagnosisTypeName) {
        this.diagnosisTypeName = diagnosisTypeName == null ? null : diagnosisTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    public String getDiagnosisOrder() {
        return diagnosisOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @param diagnosisOrder the value for V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    public void setDiagnosisOrder(String diagnosisOrder) {
        this.diagnosisOrder = diagnosisOrder == null ? null : diagnosisOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DESC
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DESC
     *
     * @mbggenerated
     */
    public String getDiagnosisDesc() {
        return diagnosisDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DESC
     *
     * @param diagnosisDesc the value for V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DESC
     *
     * @mbggenerated
     */
    public void setDiagnosisDesc(String diagnosisDesc) {
        this.diagnosisDesc = diagnosisDesc == null ? null : diagnosisDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    public Date getDiagnosisDate() {
        return diagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @param diagnosisDate the value for V_HIS_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    public void setDiagnosisDate(Date diagnosisDate) {
        this.diagnosisDate = diagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.TREAT_DAYS
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.TREAT_DAYS
     *
     * @mbggenerated
     */
    public String getTreatDays() {
        return treatDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.TREAT_DAYS
     *
     * @param treatDays the value for V_HIS_DIAGNOSIS_INFO.TREAT_DAYS
     *
     * @mbggenerated
     */
    public void setTreatDays(String treatDays) {
        this.treatDays = treatDays == null ? null : treatDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.TREAT_RESULT
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.TREAT_RESULT
     *
     * @mbggenerated
     */
    public String getTreatResult() {
        return treatResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.TREAT_RESULT
     *
     * @param treatResult the value for V_HIS_DIAGNOSIS_INFO.TREAT_RESULT
     *
     * @mbggenerated
     */
    public void setTreatResult(String treatResult) {
        this.treatResult = treatResult == null ? null : treatResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DIAGNOSIS_INFO.OPER_TREAT_INDICATOR
     *
     * @return the value of V_HIS_DIAGNOSIS_INFO.OPER_TREAT_INDICATOR
     *
     * @mbggenerated
     */
    public String getOperTreatIndicator() {
        return operTreatIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DIAGNOSIS_INFO.OPER_TREAT_INDICATOR
     *
     * @param operTreatIndicator the value for V_HIS_DIAGNOSIS_INFO.OPER_TREAT_INDICATOR
     *
     * @mbggenerated
     */
    public void setOperTreatIndicator(String operTreatIndicator) {
        this.operTreatIndicator = operTreatIndicator == null ? null : operTreatIndicator.trim();
    }
}