package com.kyee.model;

import java.util.Date;

public class VHisExamInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    private String examNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_NAME
     *
     * @mbggenerated
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_CLASS
     *
     * @mbggenerated
     */
    private String examClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_SUB_CLASS
     *
     * @mbggenerated
     */
    private String examSubClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.REQ_PHYSICIAN
     *
     * @mbggenerated
     */
    private String reqPhysician;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.REQ_DATE_TIME
     *
     * @mbggenerated
     */
    private Date reqDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    private String insDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    private String insDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    private Date examDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_DATE_TIME
     *
     * @mbggenerated
     */
    private Date examDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.REPORTER
     *
     * @mbggenerated
     */
    private String reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.REPORT_DATE_TIME
     *
     * @mbggenerated
     */
    private Date reportDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.RESULT_STATUS
     *
     * @mbggenerated
     */
    private String resultStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.TOTAL_EXPENSE
     *
     * @mbggenerated
     */
    private String totalExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.RECEIVABLE_EXPENSE
     *
     * @mbggenerated
     */
    private String receivableExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.ACTUAL_EXPENSE
     *
     * @mbggenerated
     */
    private String actualExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.CHARGE_INDICATOR
     *
     * @mbggenerated
     */
    private String chargeIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.PRESC_NO
     *
     * @mbggenerated
     */
    private String prescNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    private String examPara;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.PICTURE_STATUS
     *
     * @mbggenerated
     */
    private String pictureStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    private String examSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    private String impression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    private String recommendation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_NO
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    public String getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_NO
     *
     * @param examNo the value for V_HIS_EXAM_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    public void setExamNo(String examNo) {
        this.examNo = examNo == null ? null : examNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.PATIENT_ID
     *
     * @return the value of V_HIS_EXAM_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.PATIENT_ID
     *
     * @param patientId the value for V_HIS_EXAM_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.PATIENT_NAME
     *
     * @return the value of V_HIS_EXAM_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.PATIENT_NAME
     *
     * @param patientName the value for V_HIS_EXAM_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.ID_NO
     *
     * @return the value of V_HIS_EXAM_INFO.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.ID_NO
     *
     * @param idNo the value for V_HIS_EXAM_INFO.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.PHONE_NUMBER
     *
     * @return the value of V_HIS_EXAM_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for V_HIS_EXAM_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.VISIT_NO
     *
     * @return the value of V_HIS_EXAM_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.VISIT_NO
     *
     * @param visitNo the value for V_HIS_EXAM_INFO.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.INHOSPITAL_NO
     *
     * @return the value of V_HIS_EXAM_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_EXAM_INFO.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.OUTPATIENT_NO
     *
     * @return the value of V_HIS_EXAM_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_EXAM_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_NAME
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_NAME
     *
     * @mbggenerated
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_NAME
     *
     * @param examName the value for V_HIS_EXAM_INFO.EXAM_NAME
     *
     * @mbggenerated
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_CLASS
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_CLASS
     *
     * @mbggenerated
     */
    public String getExamClass() {
        return examClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_CLASS
     *
     * @param examClass the value for V_HIS_EXAM_INFO.EXAM_CLASS
     *
     * @mbggenerated
     */
    public void setExamClass(String examClass) {
        this.examClass = examClass == null ? null : examClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_SUB_CLASS
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_SUB_CLASS
     *
     * @mbggenerated
     */
    public String getExamSubClass() {
        return examSubClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_SUB_CLASS
     *
     * @param examSubClass the value for V_HIS_EXAM_INFO.EXAM_SUB_CLASS
     *
     * @mbggenerated
     */
    public void setExamSubClass(String examSubClass) {
        this.examSubClass = examSubClass == null ? null : examSubClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.REQ_PHYSICIAN
     *
     * @return the value of V_HIS_EXAM_INFO.REQ_PHYSICIAN
     *
     * @mbggenerated
     */
    public String getReqPhysician() {
        return reqPhysician;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.REQ_PHYSICIAN
     *
     * @param reqPhysician the value for V_HIS_EXAM_INFO.REQ_PHYSICIAN
     *
     * @mbggenerated
     */
    public void setReqPhysician(String reqPhysician) {
        this.reqPhysician = reqPhysician == null ? null : reqPhysician.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.DOCTOR_CODE
     *
     * @return the value of V_HIS_EXAM_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.DOCTOR_CODE
     *
     * @param doctorCode the value for V_HIS_EXAM_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.REQ_DATE_TIME
     *
     * @return the value of V_HIS_EXAM_INFO.REQ_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getReqDateTime() {
        return reqDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.REQ_DATE_TIME
     *
     * @param reqDateTime the value for V_HIS_EXAM_INFO.REQ_DATE_TIME
     *
     * @mbggenerated
     */
    public void setReqDateTime(Date reqDateTime) {
        this.reqDateTime = reqDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.INS_DEPT_CODE
     *
     * @return the value of V_HIS_EXAM_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getInsDeptCode() {
        return insDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.INS_DEPT_CODE
     *
     * @param insDeptCode the value for V_HIS_EXAM_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setInsDeptCode(String insDeptCode) {
        this.insDeptCode = insDeptCode == null ? null : insDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.INS_DEPT_NAME
     *
     * @return the value of V_HIS_EXAM_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public String getInsDeptName() {
        return insDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.INS_DEPT_NAME
     *
     * @param insDeptName the value for V_HIS_EXAM_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public void setInsDeptName(String insDeptName) {
        this.insDeptName = insDeptName == null ? null : insDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_DATE
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_DATE
     *
     * @param examDate the value for V_HIS_EXAM_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_DATE_TIME
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getExamDateTime() {
        return examDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_DATE_TIME
     *
     * @param examDateTime the value for V_HIS_EXAM_INFO.EXAM_DATE_TIME
     *
     * @mbggenerated
     */
    public void setExamDateTime(Date examDateTime) {
        this.examDateTime = examDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.REPORTER
     *
     * @return the value of V_HIS_EXAM_INFO.REPORTER
     *
     * @mbggenerated
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.REPORTER
     *
     * @param reporter the value for V_HIS_EXAM_INFO.REPORTER
     *
     * @mbggenerated
     */
    public void setReporter(String reporter) {
        this.reporter = reporter == null ? null : reporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.REPORT_DATE_TIME
     *
     * @return the value of V_HIS_EXAM_INFO.REPORT_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getReportDateTime() {
        return reportDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.REPORT_DATE_TIME
     *
     * @param reportDateTime the value for V_HIS_EXAM_INFO.REPORT_DATE_TIME
     *
     * @mbggenerated
     */
    public void setReportDateTime(Date reportDateTime) {
        this.reportDateTime = reportDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.RESULT_STATUS
     *
     * @return the value of V_HIS_EXAM_INFO.RESULT_STATUS
     *
     * @mbggenerated
     */
    public String getResultStatus() {
        return resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.RESULT_STATUS
     *
     * @param resultStatus the value for V_HIS_EXAM_INFO.RESULT_STATUS
     *
     * @mbggenerated
     */
    public void setResultStatus(String resultStatus) {
        this.resultStatus = resultStatus == null ? null : resultStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.TOTAL_EXPENSE
     *
     * @return the value of V_HIS_EXAM_INFO.TOTAL_EXPENSE
     *
     * @mbggenerated
     */
    public String getTotalExpense() {
        return totalExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.TOTAL_EXPENSE
     *
     * @param totalExpense the value for V_HIS_EXAM_INFO.TOTAL_EXPENSE
     *
     * @mbggenerated
     */
    public void setTotalExpense(String totalExpense) {
        this.totalExpense = totalExpense == null ? null : totalExpense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.RECEIVABLE_EXPENSE
     *
     * @return the value of V_HIS_EXAM_INFO.RECEIVABLE_EXPENSE
     *
     * @mbggenerated
     */
    public String getReceivableExpense() {
        return receivableExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.RECEIVABLE_EXPENSE
     *
     * @param receivableExpense the value for V_HIS_EXAM_INFO.RECEIVABLE_EXPENSE
     *
     * @mbggenerated
     */
    public void setReceivableExpense(String receivableExpense) {
        this.receivableExpense = receivableExpense == null ? null : receivableExpense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.ACTUAL_EXPENSE
     *
     * @return the value of V_HIS_EXAM_INFO.ACTUAL_EXPENSE
     *
     * @mbggenerated
     */
    public String getActualExpense() {
        return actualExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.ACTUAL_EXPENSE
     *
     * @param actualExpense the value for V_HIS_EXAM_INFO.ACTUAL_EXPENSE
     *
     * @mbggenerated
     */
    public void setActualExpense(String actualExpense) {
        this.actualExpense = actualExpense == null ? null : actualExpense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.CHARGE_INDICATOR
     *
     * @return the value of V_HIS_EXAM_INFO.CHARGE_INDICATOR
     *
     * @mbggenerated
     */
    public String getChargeIndicator() {
        return chargeIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.CHARGE_INDICATOR
     *
     * @param chargeIndicator the value for V_HIS_EXAM_INFO.CHARGE_INDICATOR
     *
     * @mbggenerated
     */
    public void setChargeIndicator(String chargeIndicator) {
        this.chargeIndicator = chargeIndicator == null ? null : chargeIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.PRESC_NO
     *
     * @return the value of V_HIS_EXAM_INFO.PRESC_NO
     *
     * @mbggenerated
     */
    public String getPrescNo() {
        return prescNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.PRESC_NO
     *
     * @param prescNo the value for V_HIS_EXAM_INFO.PRESC_NO
     *
     * @mbggenerated
     */
    public void setPrescNo(String prescNo) {
        this.prescNo = prescNo == null ? null : prescNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_PARA
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    public String getExamPara() {
        return examPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_PARA
     *
     * @param examPara the value for V_HIS_EXAM_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    public void setExamPara(String examPara) {
        this.examPara = examPara == null ? null : examPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.PICTURE_STATUS
     *
     * @return the value of V_HIS_EXAM_INFO.PICTURE_STATUS
     *
     * @mbggenerated
     */
    public String getPictureStatus() {
        return pictureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.PICTURE_STATUS
     *
     * @param pictureStatus the value for V_HIS_EXAM_INFO.PICTURE_STATUS
     *
     * @mbggenerated
     */
    public void setPictureStatus(String pictureStatus) {
        this.pictureStatus = pictureStatus == null ? null : pictureStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.EXAM_SOURCE
     *
     * @return the value of V_HIS_EXAM_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    public String getExamSource() {
        return examSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.EXAM_SOURCE
     *
     * @param examSource the value for V_HIS_EXAM_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    public void setExamSource(String examSource) {
        this.examSource = examSource == null ? null : examSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.DESCRIPTION
     *
     * @return the value of V_HIS_EXAM_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.DESCRIPTION
     *
     * @param description the value for V_HIS_EXAM_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.IMPRESSION
     *
     * @return the value of V_HIS_EXAM_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    public String getImpression() {
        return impression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.IMPRESSION
     *
     * @param impression the value for V_HIS_EXAM_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    public void setImpression(String impression) {
        this.impression = impression == null ? null : impression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_INFO.RECOMMENDATION
     *
     * @return the value of V_HIS_EXAM_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    public String getRecommendation() {
        return recommendation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_INFO.RECOMMENDATION
     *
     * @param recommendation the value for V_HIS_EXAM_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation == null ? null : recommendation.trim();
    }
}