package com.kyee.model;

import java.util.Date;

public class VHisDischargeSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    private String admittingDiagnosisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.X_RAY_NO
     *
     * @mbggenerated
     */
    private String xRayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.COMPLICATION
     *
     * @mbggenerated
     */
    private String complication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    private String dischargeDiagnosisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String dischargeDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.TREATMENT_RESULT
     *
     * @mbggenerated
     */
    private String treatmentResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.CLINIC_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String clinicDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    private String admittingMajorSymptomsAndSigns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String admittingDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.COURSE_AND_TREATMENT_RESULT
     *
     * @mbggenerated
     */
    private String courseAndTreatmentResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.MAJOR_TEST_RESULT
     *
     * @mbggenerated
     */
    private String majorTestResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.SPECIAL_INSPECTION_AND_CONSULTATION
     *
     * @mbggenerated
     */
    private String specialInspectionAndConsultation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    private String dischargeMajorSymptomsAndSigns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    private String postDischargeMedicationAndSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_ORTHER_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    private String postDischargeOrtherMedicationAndSuggestion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.PATIENT_ID
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.PATIENT_ID
     *
     * @param patientId the value for V_HIS_DISCHARGE_SUMMARY.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.VISIT_NO
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.VISIT_NO
     *
     * @param visitNo the value for V_HIS_DISCHARGE_SUMMARY.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.INHOSPITAL_NO
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_DISCHARGE_SUMMARY.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS_CODE
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public String getAdmittingDiagnosisCode() {
        return admittingDiagnosisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS_CODE
     *
     * @param admittingDiagnosisCode the value for V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public void setAdmittingDiagnosisCode(String admittingDiagnosisCode) {
        this.admittingDiagnosisCode = admittingDiagnosisCode == null ? null : admittingDiagnosisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.X_RAY_NO
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.X_RAY_NO
     *
     * @mbggenerated
     */
    public String getxRayNo() {
        return xRayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.X_RAY_NO
     *
     * @param xRayNo the value for V_HIS_DISCHARGE_SUMMARY.X_RAY_NO
     *
     * @mbggenerated
     */
    public void setxRayNo(String xRayNo) {
        this.xRayNo = xRayNo == null ? null : xRayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.COMPLICATION
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.COMPLICATION
     *
     * @mbggenerated
     */
    public String getComplication() {
        return complication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.COMPLICATION
     *
     * @param complication the value for V_HIS_DISCHARGE_SUMMARY.COMPLICATION
     *
     * @mbggenerated
     */
    public void setComplication(String complication) {
        this.complication = complication == null ? null : complication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS_CODE
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public String getDischargeDiagnosisCode() {
        return dischargeDiagnosisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS_CODE
     *
     * @param dischargeDiagnosisCode the value for V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public void setDischargeDiagnosisCode(String dischargeDiagnosisCode) {
        this.dischargeDiagnosisCode = dischargeDiagnosisCode == null ? null : dischargeDiagnosisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getDischargeDiagnosis() {
        return dischargeDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS
     *
     * @param dischargeDiagnosis the value for V_HIS_DISCHARGE_SUMMARY.DISCHARGE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setDischargeDiagnosis(String dischargeDiagnosis) {
        this.dischargeDiagnosis = dischargeDiagnosis == null ? null : dischargeDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.TREATMENT_RESULT
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.TREATMENT_RESULT
     *
     * @mbggenerated
     */
    public String getTreatmentResult() {
        return treatmentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.TREATMENT_RESULT
     *
     * @param treatmentResult the value for V_HIS_DISCHARGE_SUMMARY.TREATMENT_RESULT
     *
     * @mbggenerated
     */
    public void setTreatmentResult(String treatmentResult) {
        this.treatmentResult = treatmentResult == null ? null : treatmentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.CREATE_TIME
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.CREATE_TIME
     *
     * @param createTime the value for V_HIS_DISCHARGE_SUMMARY.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.CLINIC_DIAGNOSIS
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.CLINIC_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getClinicDiagnosis() {
        return clinicDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.CLINIC_DIAGNOSIS
     *
     * @param clinicDiagnosis the value for V_HIS_DISCHARGE_SUMMARY.CLINIC_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setClinicDiagnosis(String clinicDiagnosis) {
        this.clinicDiagnosis = clinicDiagnosis == null ? null : clinicDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.ADMITTING_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    public String getAdmittingMajorSymptomsAndSigns() {
        return admittingMajorSymptomsAndSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @param admittingMajorSymptomsAndSigns the value for V_HIS_DISCHARGE_SUMMARY.ADMITTING_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    public void setAdmittingMajorSymptomsAndSigns(String admittingMajorSymptomsAndSigns) {
        this.admittingMajorSymptomsAndSigns = admittingMajorSymptomsAndSigns == null ? null : admittingMajorSymptomsAndSigns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getAdmittingDiagnosis() {
        return admittingDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS
     *
     * @param admittingDiagnosis the value for V_HIS_DISCHARGE_SUMMARY.ADMITTING_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setAdmittingDiagnosis(String admittingDiagnosis) {
        this.admittingDiagnosis = admittingDiagnosis == null ? null : admittingDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.COURSE_AND_TREATMENT_RESULT
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.COURSE_AND_TREATMENT_RESULT
     *
     * @mbggenerated
     */
    public String getCourseAndTreatmentResult() {
        return courseAndTreatmentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.COURSE_AND_TREATMENT_RESULT
     *
     * @param courseAndTreatmentResult the value for V_HIS_DISCHARGE_SUMMARY.COURSE_AND_TREATMENT_RESULT
     *
     * @mbggenerated
     */
    public void setCourseAndTreatmentResult(String courseAndTreatmentResult) {
        this.courseAndTreatmentResult = courseAndTreatmentResult == null ? null : courseAndTreatmentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.MAJOR_TEST_RESULT
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.MAJOR_TEST_RESULT
     *
     * @mbggenerated
     */
    public String getMajorTestResult() {
        return majorTestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.MAJOR_TEST_RESULT
     *
     * @param majorTestResult the value for V_HIS_DISCHARGE_SUMMARY.MAJOR_TEST_RESULT
     *
     * @mbggenerated
     */
    public void setMajorTestResult(String majorTestResult) {
        this.majorTestResult = majorTestResult == null ? null : majorTestResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.SPECIAL_INSPECTION_AND_CONSULTATION
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.SPECIAL_INSPECTION_AND_CONSULTATION
     *
     * @mbggenerated
     */
    public String getSpecialInspectionAndConsultation() {
        return specialInspectionAndConsultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.SPECIAL_INSPECTION_AND_CONSULTATION
     *
     * @param specialInspectionAndConsultation the value for V_HIS_DISCHARGE_SUMMARY.SPECIAL_INSPECTION_AND_CONSULTATION
     *
     * @mbggenerated
     */
    public void setSpecialInspectionAndConsultation(String specialInspectionAndConsultation) {
        this.specialInspectionAndConsultation = specialInspectionAndConsultation == null ? null : specialInspectionAndConsultation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.DISCHARGE_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    public String getDischargeMajorSymptomsAndSigns() {
        return dischargeMajorSymptomsAndSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.DISCHARGE_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @param dischargeMajorSymptomsAndSigns the value for V_HIS_DISCHARGE_SUMMARY.DISCHARGE_MAJOR_SYMPTOMS_AND_SIGNS
     *
     * @mbggenerated
     */
    public void setDischargeMajorSymptomsAndSigns(String dischargeMajorSymptomsAndSigns) {
        this.dischargeMajorSymptomsAndSigns = dischargeMajorSymptomsAndSigns == null ? null : dischargeMajorSymptomsAndSigns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_MEDICATION_AND_SUGGESTION
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    public String getPostDischargeMedicationAndSuggestion() {
        return postDischargeMedicationAndSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_MEDICATION_AND_SUGGESTION
     *
     * @param postDischargeMedicationAndSuggestion the value for V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    public void setPostDischargeMedicationAndSuggestion(String postDischargeMedicationAndSuggestion) {
        this.postDischargeMedicationAndSuggestion = postDischargeMedicationAndSuggestion == null ? null : postDischargeMedicationAndSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_ORTHER_MEDICATION_AND_SUGGESTION
     *
     * @return the value of V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_ORTHER_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    public String getPostDischargeOrtherMedicationAndSuggestion() {
        return postDischargeOrtherMedicationAndSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_ORTHER_MEDICATION_AND_SUGGESTION
     *
     * @param postDischargeOrtherMedicationAndSuggestion the value for V_HIS_DISCHARGE_SUMMARY.POST_DISCHARGE_ORTHER_MEDICATION_AND_SUGGESTION
     *
     * @mbggenerated
     */
    public void setPostDischargeOrtherMedicationAndSuggestion(String postDischargeOrtherMedicationAndSuggestion) {
        this.postDischargeOrtherMedicationAndSuggestion = postDischargeOrtherMedicationAndSuggestion == null ? null : postDischargeOrtherMedicationAndSuggestion.trim();
    }
}