package com.kyee.model;

public class VHisOperationDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.OPERATION_DETAIL_ID
     *
     * @mbggenerated
     */
    private String operationDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    private String operationMainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    private String patientSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT_ID
     *
     * @mbggenerated
     */
    private String firstAssistantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT
     *
     * @mbggenerated
     */
    private String firstAssistant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT_ID
     *
     * @mbggenerated
     */
    private String secondAssistantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT
     *
     * @mbggenerated
     */
    private String secondAssistant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT_ID
     *
     * @mbggenerated
     */
    private String thirdAssistantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT
     *
     * @mbggenerated
     */
    private String thirdAssistant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_METHODS
     *
     * @mbggenerated
     */
    private String anesthesiaMethods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_DOSAGE
     *
     * @mbggenerated
     */
    private String anesthesiaDosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.ANESTHETIST_ID
     *
     * @mbggenerated
     */
    private String anesthetistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.ANESTHETIST
     *
     * @mbggenerated
     */
    private String anesthetist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE_ID
     *
     * @mbggenerated
     */
    private String instrumentNurseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE
     *
     * @mbggenerated
     */
    private String instrumentNurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.PREOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String preoperativeDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.INTRAOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String intraoperativeDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.POSTOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String postoperativeDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_DETAIL.OPERATION_PROCEDURE
     *
     * @mbggenerated
     */
    private String operationProcedure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_DETAIL_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.OPERATION_DETAIL_ID
     *
     * @mbggenerated
     */
    public String getOperationDetailId() {
        return operationDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_DETAIL_ID
     *
     * @param operationDetailId the value for V_HIS_OPERATION_DETAIL.OPERATION_DETAIL_ID
     *
     * @mbggenerated
     */
    public void setOperationDetailId(String operationDetailId) {
        this.operationDetailId = operationDetailId == null ? null : operationDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_MAIN_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    public String getOperationMainId() {
        return operationMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_MAIN_ID
     *
     * @param operationMainId the value for V_HIS_OPERATION_DETAIL.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    public void setOperationMainId(String operationMainId) {
        this.operationMainId = operationMainId == null ? null : operationMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.PATIENT_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.PATIENT_ID
     *
     * @param patientId the value for V_HIS_OPERATION_DETAIL.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.VISIT_NO
     *
     * @return the value of V_HIS_OPERATION_DETAIL.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.VISIT_NO
     *
     * @param visitNo the value for V_HIS_OPERATION_DETAIL.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.INHOSPITAL_NO
     *
     * @return the value of V_HIS_OPERATION_DETAIL.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_OPERATION_DETAIL.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.OUTPATIENT_NO
     *
     * @return the value of V_HIS_OPERATION_DETAIL.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_OPERATION_DETAIL.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.PATIENT_SOURCE
     *
     * @return the value of V_HIS_OPERATION_DETAIL.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public String getPatientSource() {
        return patientSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.PATIENT_SOURCE
     *
     * @param patientSource the value for V_HIS_OPERATION_DETAIL.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public void setPatientSource(String patientSource) {
        this.patientSource = patientSource == null ? null : patientSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.DEPT_CODE
     *
     * @return the value of V_HIS_OPERATION_DETAIL.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.DEPT_CODE
     *
     * @param deptCode the value for V_HIS_OPERATION_DETAIL.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.DEPT_NAME
     *
     * @return the value of V_HIS_OPERATION_DETAIL.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.DEPT_NAME
     *
     * @param deptName the value for V_HIS_OPERATION_DETAIL.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public String getFirstAssistantId() {
        return firstAssistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT_ID
     *
     * @param firstAssistantId the value for V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public void setFirstAssistantId(String firstAssistantId) {
        this.firstAssistantId = firstAssistantId == null ? null : firstAssistantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT
     *
     * @return the value of V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT
     *
     * @mbggenerated
     */
    public String getFirstAssistant() {
        return firstAssistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT
     *
     * @param firstAssistant the value for V_HIS_OPERATION_DETAIL.FIRST_ASSISTANT
     *
     * @mbggenerated
     */
    public void setFirstAssistant(String firstAssistant) {
        this.firstAssistant = firstAssistant == null ? null : firstAssistant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public String getSecondAssistantId() {
        return secondAssistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT_ID
     *
     * @param secondAssistantId the value for V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public void setSecondAssistantId(String secondAssistantId) {
        this.secondAssistantId = secondAssistantId == null ? null : secondAssistantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT
     *
     * @return the value of V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT
     *
     * @mbggenerated
     */
    public String getSecondAssistant() {
        return secondAssistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT
     *
     * @param secondAssistant the value for V_HIS_OPERATION_DETAIL.SECOND_ASSISTANT
     *
     * @mbggenerated
     */
    public void setSecondAssistant(String secondAssistant) {
        this.secondAssistant = secondAssistant == null ? null : secondAssistant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public String getThirdAssistantId() {
        return thirdAssistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT_ID
     *
     * @param thirdAssistantId the value for V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT_ID
     *
     * @mbggenerated
     */
    public void setThirdAssistantId(String thirdAssistantId) {
        this.thirdAssistantId = thirdAssistantId == null ? null : thirdAssistantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT
     *
     * @return the value of V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT
     *
     * @mbggenerated
     */
    public String getThirdAssistant() {
        return thirdAssistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT
     *
     * @param thirdAssistant the value for V_HIS_OPERATION_DETAIL.THIRD_ASSISTANT
     *
     * @mbggenerated
     */
    public void setThirdAssistant(String thirdAssistant) {
        this.thirdAssistant = thirdAssistant == null ? null : thirdAssistant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_METHODS
     *
     * @return the value of V_HIS_OPERATION_DETAIL.ANESTHESIA_METHODS
     *
     * @mbggenerated
     */
    public String getAnesthesiaMethods() {
        return anesthesiaMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_METHODS
     *
     * @param anesthesiaMethods the value for V_HIS_OPERATION_DETAIL.ANESTHESIA_METHODS
     *
     * @mbggenerated
     */
    public void setAnesthesiaMethods(String anesthesiaMethods) {
        this.anesthesiaMethods = anesthesiaMethods == null ? null : anesthesiaMethods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_DOSAGE
     *
     * @return the value of V_HIS_OPERATION_DETAIL.ANESTHESIA_DOSAGE
     *
     * @mbggenerated
     */
    public String getAnesthesiaDosage() {
        return anesthesiaDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.ANESTHESIA_DOSAGE
     *
     * @param anesthesiaDosage the value for V_HIS_OPERATION_DETAIL.ANESTHESIA_DOSAGE
     *
     * @mbggenerated
     */
    public void setAnesthesiaDosage(String anesthesiaDosage) {
        this.anesthesiaDosage = anesthesiaDosage == null ? null : anesthesiaDosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.ANESTHETIST_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.ANESTHETIST_ID
     *
     * @mbggenerated
     */
    public String getAnesthetistId() {
        return anesthetistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.ANESTHETIST_ID
     *
     * @param anesthetistId the value for V_HIS_OPERATION_DETAIL.ANESTHETIST_ID
     *
     * @mbggenerated
     */
    public void setAnesthetistId(String anesthetistId) {
        this.anesthetistId = anesthetistId == null ? null : anesthetistId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.ANESTHETIST
     *
     * @return the value of V_HIS_OPERATION_DETAIL.ANESTHETIST
     *
     * @mbggenerated
     */
    public String getAnesthetist() {
        return anesthetist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.ANESTHETIST
     *
     * @param anesthetist the value for V_HIS_OPERATION_DETAIL.ANESTHETIST
     *
     * @mbggenerated
     */
    public void setAnesthetist(String anesthetist) {
        this.anesthetist = anesthetist == null ? null : anesthetist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE_ID
     *
     * @return the value of V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE_ID
     *
     * @mbggenerated
     */
    public String getInstrumentNurseId() {
        return instrumentNurseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE_ID
     *
     * @param instrumentNurseId the value for V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE_ID
     *
     * @mbggenerated
     */
    public void setInstrumentNurseId(String instrumentNurseId) {
        this.instrumentNurseId = instrumentNurseId == null ? null : instrumentNurseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE
     *
     * @return the value of V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE
     *
     * @mbggenerated
     */
    public String getInstrumentNurse() {
        return instrumentNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE
     *
     * @param instrumentNurse the value for V_HIS_OPERATION_DETAIL.INSTRUMENT_NURSE
     *
     * @mbggenerated
     */
    public void setInstrumentNurse(String instrumentNurse) {
        this.instrumentNurse = instrumentNurse == null ? null : instrumentNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.PREOPERATIVE_DIAGNOSIS
     *
     * @return the value of V_HIS_OPERATION_DETAIL.PREOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getPreoperativeDiagnosis() {
        return preoperativeDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.PREOPERATIVE_DIAGNOSIS
     *
     * @param preoperativeDiagnosis the value for V_HIS_OPERATION_DETAIL.PREOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setPreoperativeDiagnosis(String preoperativeDiagnosis) {
        this.preoperativeDiagnosis = preoperativeDiagnosis == null ? null : preoperativeDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.INTRAOPERATIVE_DIAGNOSIS
     *
     * @return the value of V_HIS_OPERATION_DETAIL.INTRAOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getIntraoperativeDiagnosis() {
        return intraoperativeDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.INTRAOPERATIVE_DIAGNOSIS
     *
     * @param intraoperativeDiagnosis the value for V_HIS_OPERATION_DETAIL.INTRAOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setIntraoperativeDiagnosis(String intraoperativeDiagnosis) {
        this.intraoperativeDiagnosis = intraoperativeDiagnosis == null ? null : intraoperativeDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.POSTOPERATIVE_DIAGNOSIS
     *
     * @return the value of V_HIS_OPERATION_DETAIL.POSTOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public String getPostoperativeDiagnosis() {
        return postoperativeDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.POSTOPERATIVE_DIAGNOSIS
     *
     * @param postoperativeDiagnosis the value for V_HIS_OPERATION_DETAIL.POSTOPERATIVE_DIAGNOSIS
     *
     * @mbggenerated
     */
    public void setPostoperativeDiagnosis(String postoperativeDiagnosis) {
        this.postoperativeDiagnosis = postoperativeDiagnosis == null ? null : postoperativeDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_PROCEDURE
     *
     * @return the value of V_HIS_OPERATION_DETAIL.OPERATION_PROCEDURE
     *
     * @mbggenerated
     */
    public String getOperationProcedure() {
        return operationProcedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_DETAIL.OPERATION_PROCEDURE
     *
     * @param operationProcedure the value for V_HIS_OPERATION_DETAIL.OPERATION_PROCEDURE
     *
     * @mbggenerated
     */
    public void setOperationProcedure(String operationProcedure) {
        this.operationProcedure = operationProcedure == null ? null : operationProcedure.trim();
    }
}