package com.kyee.model;

import java.util.Date;

public class VHisUsersInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.PINYIN_CODE
     *
     * @mbggenerated
     */
    private String pinyinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.PHONE_NO
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.MAILBOX
     *
     * @mbggenerated
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.TITLE_CODE
     *
     * @mbggenerated
     */
    private String titleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.TITLE_NAME
     *
     * @mbggenerated
     */
    private String titleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.POSITION
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USERS_INFO.SUMMARY
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.USER_ID
     *
     * @return the value of V_HIS_USERS_INFO.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.USER_ID
     *
     * @param userId the value for V_HIS_USERS_INFO.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.USER_NAME
     *
     * @return the value of V_HIS_USERS_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.USER_NAME
     *
     * @param userName the value for V_HIS_USERS_INFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.ACCOUNT
     *
     * @return the value of V_HIS_USERS_INFO.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.ACCOUNT
     *
     * @param account the value for V_HIS_USERS_INFO.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.PASSWORD
     *
     * @return the value of V_HIS_USERS_INFO.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.PASSWORD
     *
     * @param password the value for V_HIS_USERS_INFO.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.PINYIN_CODE
     *
     * @return the value of V_HIS_USERS_INFO.PINYIN_CODE
     *
     * @mbggenerated
     */
    public String getPinyinCode() {
        return pinyinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.PINYIN_CODE
     *
     * @param pinyinCode the value for V_HIS_USERS_INFO.PINYIN_CODE
     *
     * @mbggenerated
     */
    public void setPinyinCode(String pinyinCode) {
        this.pinyinCode = pinyinCode == null ? null : pinyinCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.PHONE_NO
     *
     * @return the value of V_HIS_USERS_INFO.PHONE_NO
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.PHONE_NO
     *
     * @param phoneNo the value for V_HIS_USERS_INFO.PHONE_NO
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.ID_NO
     *
     * @return the value of V_HIS_USERS_INFO.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.ID_NO
     *
     * @param idNo the value for V_HIS_USERS_INFO.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.SEX
     *
     * @return the value of V_HIS_USERS_INFO.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.SEX
     *
     * @param sex the value for V_HIS_USERS_INFO.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.BIRTHDAY
     *
     * @return the value of V_HIS_USERS_INFO.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.BIRTHDAY
     *
     * @param birthday the value for V_HIS_USERS_INFO.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.MAILBOX
     *
     * @return the value of V_HIS_USERS_INFO.MAILBOX
     *
     * @mbggenerated
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.MAILBOX
     *
     * @param mailbox the value for V_HIS_USERS_INFO.MAILBOX
     *
     * @mbggenerated
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.TITLE_CODE
     *
     * @return the value of V_HIS_USERS_INFO.TITLE_CODE
     *
     * @mbggenerated
     */
    public String getTitleCode() {
        return titleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.TITLE_CODE
     *
     * @param titleCode the value for V_HIS_USERS_INFO.TITLE_CODE
     *
     * @mbggenerated
     */
    public void setTitleCode(String titleCode) {
        this.titleCode = titleCode == null ? null : titleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.TITLE_NAME
     *
     * @return the value of V_HIS_USERS_INFO.TITLE_NAME
     *
     * @mbggenerated
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.TITLE_NAME
     *
     * @param titleName the value for V_HIS_USERS_INFO.TITLE_NAME
     *
     * @mbggenerated
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName == null ? null : titleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.POSITION
     *
     * @return the value of V_HIS_USERS_INFO.POSITION
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.POSITION
     *
     * @param position the value for V_HIS_USERS_INFO.POSITION
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USERS_INFO.SUMMARY
     *
     * @return the value of V_HIS_USERS_INFO.SUMMARY
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USERS_INFO.SUMMARY
     *
     * @param summary the value for V_HIS_USERS_INFO.SUMMARY
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }
}