package com.kyee.model;

import java.util.Date;

public class VHisOperationMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    private String operationMainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.VISIT_NO
     *
     * @mbggenerated
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    private String inhospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    private String patientSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OPERATION_NAME
     *
     * @mbggenerated
     */
    private String operationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OPERATOR_ID
     *
     * @mbggenerated
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_OPERATION_MAIN.OPERATION_DATE
     *
     * @mbggenerated
     */
    private Date operationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OPERATION_MAIN_ID
     *
     * @return the value of V_HIS_OPERATION_MAIN.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    public String getOperationMainId() {
        return operationMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OPERATION_MAIN_ID
     *
     * @param operationMainId the value for V_HIS_OPERATION_MAIN.OPERATION_MAIN_ID
     *
     * @mbggenerated
     */
    public void setOperationMainId(String operationMainId) {
        this.operationMainId = operationMainId == null ? null : operationMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.PATIENT_ID
     *
     * @return the value of V_HIS_OPERATION_MAIN.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.PATIENT_ID
     *
     * @param patientId the value for V_HIS_OPERATION_MAIN.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.VISIT_NO
     *
     * @return the value of V_HIS_OPERATION_MAIN.VISIT_NO
     *
     * @mbggenerated
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.VISIT_NO
     *
     * @param visitNo the value for V_HIS_OPERATION_MAIN.VISIT_NO
     *
     * @mbggenerated
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.INHOSPITAL_NO
     *
     * @return the value of V_HIS_OPERATION_MAIN.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public String getInhospitalNo() {
        return inhospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.INHOSPITAL_NO
     *
     * @param inhospitalNo the value for V_HIS_OPERATION_MAIN.INHOSPITAL_NO
     *
     * @mbggenerated
     */
    public void setInhospitalNo(String inhospitalNo) {
        this.inhospitalNo = inhospitalNo == null ? null : inhospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OUTPATIENT_NO
     *
     * @return the value of V_HIS_OPERATION_MAIN.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_OPERATION_MAIN.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.PATIENT_SOURCE
     *
     * @return the value of V_HIS_OPERATION_MAIN.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public String getPatientSource() {
        return patientSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.PATIENT_SOURCE
     *
     * @param patientSource the value for V_HIS_OPERATION_MAIN.PATIENT_SOURCE
     *
     * @mbggenerated
     */
    public void setPatientSource(String patientSource) {
        this.patientSource = patientSource == null ? null : patientSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OPERATION_NAME
     *
     * @return the value of V_HIS_OPERATION_MAIN.OPERATION_NAME
     *
     * @mbggenerated
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OPERATION_NAME
     *
     * @param operationName the value for V_HIS_OPERATION_MAIN.OPERATION_NAME
     *
     * @mbggenerated
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName == null ? null : operationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OPERATOR_ID
     *
     * @return the value of V_HIS_OPERATION_MAIN.OPERATOR_ID
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OPERATOR_ID
     *
     * @param operatorId the value for V_HIS_OPERATION_MAIN.OPERATOR_ID
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OPERATOR
     *
     * @return the value of V_HIS_OPERATION_MAIN.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OPERATOR
     *
     * @param operator the value for V_HIS_OPERATION_MAIN.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_OPERATION_MAIN.OPERATION_DATE
     *
     * @return the value of V_HIS_OPERATION_MAIN.OPERATION_DATE
     *
     * @mbggenerated
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_OPERATION_MAIN.OPERATION_DATE
     *
     * @param operationDate the value for V_HIS_OPERATION_MAIN.OPERATION_DATE
     *
     * @mbggenerated
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }
}