package com.kyee.model;

import java.util.Date;

public class VHisClinicDiagnosisInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    private String diagnosisOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    private Date diagnosisDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSTIC_TYPES
     *
     * @mbggenerated
     */
    private String diagnosticTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    private String icdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_NAME
     *
     * @mbggenerated
     */
    private String icdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_RESULT
     *
     * @mbggenerated
     */
    private String diagnosisResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BODY_WEIGHT
     *
     * @mbggenerated
     */
    private String bodyWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TEMPERATURE
     *
     * @mbggenerated
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PULSE
     *
     * @mbggenerated
     */
    private String pulse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.RESPIRATION
     *
     * @mbggenerated
     */
    private String respiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_LOW
     *
     * @mbggenerated
     */
    private String bloodPressureLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_HIGH
     *
     * @mbggenerated
     */
    private String bloodPressureHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.CHIET_COMPLAINT
     *
     * @mbggenerated
     */
    private String chietComplaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRESENT_HISTORY
     *
     * @mbggenerated
     */
    private String presentHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PAST_HISTORY
     *
     * @mbggenerated
     */
    private String pastHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DRUG_ALLERGY_HISTORY
     *
     * @mbggenerated
     */
    private String drugAllergyHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TREATED
     *
     * @mbggenerated
     */
    private String treated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRECAUTIONS
     *
     * @mbggenerated
     */
    private String precautions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    private String diagnosisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    private String diagnosisName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.QUERYBODY
     *
     * @mbggenerated
     */
    private String querybody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ONSET_DATE
     *
     * @mbggenerated
     */
    private String onsetDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_DOUBT
     *
     * @mbggenerated
     */
    private String isDoubt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_REFERRAL
     *
     * @mbggenerated
     */
    private String isReferral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_DIAGNOSIS_INFO.SUGGEST
     *
     * @mbggenerated
     */
    private String suggest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @param patientId the value for V_HIS_CLINIC_DIAGNOSIS_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.OUTPATIENT_NO
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_CLINIC_DIAGNOSIS_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    public String getDiagnosisOrder() {
        return diagnosisOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @param diagnosisOrder the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_ORDER
     *
     * @mbggenerated
     */
    public void setDiagnosisOrder(String diagnosisOrder) {
        this.diagnosisOrder = diagnosisOrder == null ? null : diagnosisOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    public Date getDiagnosisDate() {
        return diagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @param diagnosisDate the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_DATE
     *
     * @mbggenerated
     */
    public void setDiagnosisDate(Date diagnosisDate) {
        this.diagnosisDate = diagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_CODE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_CODE
     *
     * @param deptCode the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_NAME
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_NAME
     *
     * @param deptName the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_CODE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_CODE
     *
     * @param doctorCode the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_NAME
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_NAME
     *
     * @param doctorName the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSTIC_TYPES
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSTIC_TYPES
     *
     * @mbggenerated
     */
    public String getDiagnosticTypes() {
        return diagnosticTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSTIC_TYPES
     *
     * @param diagnosticTypes the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSTIC_TYPES
     *
     * @mbggenerated
     */
    public void setDiagnosticTypes(String diagnosticTypes) {
        this.diagnosticTypes = diagnosticTypes == null ? null : diagnosticTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_CODE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    public String getIcdCode() {
        return icdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_CODE
     *
     * @param icdCode the value for V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_CODE
     *
     * @mbggenerated
     */
    public void setIcdCode(String icdCode) {
        this.icdCode = icdCode == null ? null : icdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_NAME
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_NAME
     *
     * @mbggenerated
     */
    public String getIcdName() {
        return icdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_NAME
     *
     * @param icdName the value for V_HIS_CLINIC_DIAGNOSIS_INFO.ICD_NAME
     *
     * @mbggenerated
     */
    public void setIcdName(String icdName) {
        this.icdName = icdName == null ? null : icdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_RESULT
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_RESULT
     *
     * @mbggenerated
     */
    public String getDiagnosisResult() {
        return diagnosisResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_RESULT
     *
     * @param diagnosisResult the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_RESULT
     *
     * @mbggenerated
     */
    public void setDiagnosisResult(String diagnosisResult) {
        this.diagnosisResult = diagnosisResult == null ? null : diagnosisResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BODY_WEIGHT
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.BODY_WEIGHT
     *
     * @mbggenerated
     */
    public String getBodyWeight() {
        return bodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BODY_WEIGHT
     *
     * @param bodyWeight the value for V_HIS_CLINIC_DIAGNOSIS_INFO.BODY_WEIGHT
     *
     * @mbggenerated
     */
    public void setBodyWeight(String bodyWeight) {
        this.bodyWeight = bodyWeight == null ? null : bodyWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TEMPERATURE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.TEMPERATURE
     *
     * @mbggenerated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TEMPERATURE
     *
     * @param temperature the value for V_HIS_CLINIC_DIAGNOSIS_INFO.TEMPERATURE
     *
     * @mbggenerated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PULSE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.PULSE
     *
     * @mbggenerated
     */
    public String getPulse() {
        return pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PULSE
     *
     * @param pulse the value for V_HIS_CLINIC_DIAGNOSIS_INFO.PULSE
     *
     * @mbggenerated
     */
    public void setPulse(String pulse) {
        this.pulse = pulse == null ? null : pulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.RESPIRATION
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.RESPIRATION
     *
     * @mbggenerated
     */
    public String getRespiration() {
        return respiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.RESPIRATION
     *
     * @param respiration the value for V_HIS_CLINIC_DIAGNOSIS_INFO.RESPIRATION
     *
     * @mbggenerated
     */
    public void setRespiration(String respiration) {
        this.respiration = respiration == null ? null : respiration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_LOW
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_LOW
     *
     * @mbggenerated
     */
    public String getBloodPressureLow() {
        return bloodPressureLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_LOW
     *
     * @param bloodPressureLow the value for V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_LOW
     *
     * @mbggenerated
     */
    public void setBloodPressureLow(String bloodPressureLow) {
        this.bloodPressureLow = bloodPressureLow == null ? null : bloodPressureLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_HIGH
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_HIGH
     *
     * @mbggenerated
     */
    public String getBloodPressureHigh() {
        return bloodPressureHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_HIGH
     *
     * @param bloodPressureHigh the value for V_HIS_CLINIC_DIAGNOSIS_INFO.BLOOD_PRESSURE_HIGH
     *
     * @mbggenerated
     */
    public void setBloodPressureHigh(String bloodPressureHigh) {
        this.bloodPressureHigh = bloodPressureHigh == null ? null : bloodPressureHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.CHIET_COMPLAINT
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.CHIET_COMPLAINT
     *
     * @mbggenerated
     */
    public String getChietComplaint() {
        return chietComplaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.CHIET_COMPLAINT
     *
     * @param chietComplaint the value for V_HIS_CLINIC_DIAGNOSIS_INFO.CHIET_COMPLAINT
     *
     * @mbggenerated
     */
    public void setChietComplaint(String chietComplaint) {
        this.chietComplaint = chietComplaint == null ? null : chietComplaint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRESENT_HISTORY
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.PRESENT_HISTORY
     *
     * @mbggenerated
     */
    public String getPresentHistory() {
        return presentHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRESENT_HISTORY
     *
     * @param presentHistory the value for V_HIS_CLINIC_DIAGNOSIS_INFO.PRESENT_HISTORY
     *
     * @mbggenerated
     */
    public void setPresentHistory(String presentHistory) {
        this.presentHistory = presentHistory == null ? null : presentHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PAST_HISTORY
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.PAST_HISTORY
     *
     * @mbggenerated
     */
    public String getPastHistory() {
        return pastHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PAST_HISTORY
     *
     * @param pastHistory the value for V_HIS_CLINIC_DIAGNOSIS_INFO.PAST_HISTORY
     *
     * @mbggenerated
     */
    public void setPastHistory(String pastHistory) {
        this.pastHistory = pastHistory == null ? null : pastHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DRUG_ALLERGY_HISTORY
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DRUG_ALLERGY_HISTORY
     *
     * @mbggenerated
     */
    public String getDrugAllergyHistory() {
        return drugAllergyHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DRUG_ALLERGY_HISTORY
     *
     * @param drugAllergyHistory the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DRUG_ALLERGY_HISTORY
     *
     * @mbggenerated
     */
    public void setDrugAllergyHistory(String drugAllergyHistory) {
        this.drugAllergyHistory = drugAllergyHistory == null ? null : drugAllergyHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TREATED
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.TREATED
     *
     * @mbggenerated
     */
    public String getTreated() {
        return treated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.TREATED
     *
     * @param treated the value for V_HIS_CLINIC_DIAGNOSIS_INFO.TREATED
     *
     * @mbggenerated
     */
    public void setTreated(String treated) {
        this.treated = treated == null ? null : treated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRECAUTIONS
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.PRECAUTIONS
     *
     * @mbggenerated
     */
    public String getPrecautions() {
        return precautions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.PRECAUTIONS
     *
     * @param precautions the value for V_HIS_CLINIC_DIAGNOSIS_INFO.PRECAUTIONS
     *
     * @mbggenerated
     */
    public void setPrecautions(String precautions) {
        this.precautions = precautions == null ? null : precautions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_CODE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public String getDiagnosisCode() {
        return diagnosisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_CODE
     *
     * @param diagnosisCode the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public void setDiagnosisCode(String diagnosisCode) {
        this.diagnosisCode = diagnosisCode == null ? null : diagnosisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_NAME
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    public String getDiagnosisName() {
        return diagnosisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_NAME
     *
     * @param diagnosisName the value for V_HIS_CLINIC_DIAGNOSIS_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    public void setDiagnosisName(String diagnosisName) {
        this.diagnosisName = diagnosisName == null ? null : diagnosisName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.QUERYBODY
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.QUERYBODY
     *
     * @mbggenerated
     */
    public String getQuerybody() {
        return querybody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.QUERYBODY
     *
     * @param querybody the value for V_HIS_CLINIC_DIAGNOSIS_INFO.QUERYBODY
     *
     * @mbggenerated
     */
    public void setQuerybody(String querybody) {
        this.querybody = querybody == null ? null : querybody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ONSET_DATE
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.ONSET_DATE
     *
     * @mbggenerated
     */
    public String getOnsetDate() {
        return onsetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.ONSET_DATE
     *
     * @param onsetDate the value for V_HIS_CLINIC_DIAGNOSIS_INFO.ONSET_DATE
     *
     * @mbggenerated
     */
    public void setOnsetDate(String onsetDate) {
        this.onsetDate = onsetDate == null ? null : onsetDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_DOUBT
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.IS_DOUBT
     *
     * @mbggenerated
     */
    public String getIsDoubt() {
        return isDoubt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_DOUBT
     *
     * @param isDoubt the value for V_HIS_CLINIC_DIAGNOSIS_INFO.IS_DOUBT
     *
     * @mbggenerated
     */
    public void setIsDoubt(String isDoubt) {
        this.isDoubt = isDoubt == null ? null : isDoubt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_REFERRAL
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.IS_REFERRAL
     *
     * @mbggenerated
     */
    public String getIsReferral() {
        return isReferral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.IS_REFERRAL
     *
     * @param isReferral the value for V_HIS_CLINIC_DIAGNOSIS_INFO.IS_REFERRAL
     *
     * @mbggenerated
     */
    public void setIsReferral(String isReferral) {
        this.isReferral = isReferral == null ? null : isReferral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.SUGGEST
     *
     * @return the value of V_HIS_CLINIC_DIAGNOSIS_INFO.SUGGEST
     *
     * @mbggenerated
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_DIAGNOSIS_INFO.SUGGEST
     *
     * @param suggest the value for V_HIS_CLINIC_DIAGNOSIS_INFO.SUGGEST
     *
     * @mbggenerated
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest == null ? null : suggest.trim();
    }
}