package com.kyee.model;

import java.util.Date;

public class VHisPhysicalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    private String physicalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.NATION
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    private String identityStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    private String chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    private String mailingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    private String nextOfKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    private String relationshipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    private String nextOfKinAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    private String nextOfKinPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    private String vipIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PHYSICAL_TIME
     *
     * @mbggenerated
     */
    private Date physicalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String totalInspectionDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String totalInspectionDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DATE
     *
     * @mbggenerated
     */
    private Date totalInspectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    private String insuranceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    private String medicalInsuranceCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    private String socialSecurityCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    private String passportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    private String rhBloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    private String workUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.OVERVIEW
     *
     * @mbggenerated
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_INFO.SUGGEST
     *
     * @mbggenerated
     */
    private String suggest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PHYSICAL_NUMBER
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public String getPhysicalNumber() {
        return physicalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PHYSICAL_NUMBER
     *
     * @param physicalNumber the value for V_HIS_PHYSICAL_INFO.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public void setPhysicalNumber(String physicalNumber) {
        this.physicalNumber = physicalNumber == null ? null : physicalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PATIENT_ID
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PATIENT_ID
     *
     * @param patientId the value for V_HIS_PHYSICAL_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PATIENT_NAME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PATIENT_NAME
     *
     * @param patientName the value for V_HIS_PHYSICAL_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.SEX
     *
     * @return the value of V_HIS_PHYSICAL_INFO.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.SEX
     *
     * @param sex the value for V_HIS_PHYSICAL_INFO.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.DATE_OF_BIRTH
     *
     * @return the value of V_HIS_PHYSICAL_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for V_HIS_PHYSICAL_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.AREA_NAME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.AREA_NAME
     *
     * @param areaName the value for V_HIS_PHYSICAL_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.COUNTRY_NAME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.COUNTRY_NAME
     *
     * @param countryName the value for V_HIS_PHYSICAL_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.NATION
     *
     * @return the value of V_HIS_PHYSICAL_INFO.NATION
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.NATION
     *
     * @param nation the value for V_HIS_PHYSICAL_INFO.NATION
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.ID_NO
     *
     * @return the value of V_HIS_PHYSICAL_INFO.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.ID_NO
     *
     * @param idNo the value for V_HIS_PHYSICAL_INFO.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.IDENTITY_STR
     *
     * @return the value of V_HIS_PHYSICAL_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    public String getIdentityStr() {
        return identityStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.IDENTITY_STR
     *
     * @param identityStr the value for V_HIS_PHYSICAL_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    public void setIdentityStr(String identityStr) {
        this.identityStr = identityStr == null ? null : identityStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.CHARGE_TYPE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.CHARGE_TYPE
     *
     * @param chargeType the value for V_HIS_PHYSICAL_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.MAILING_ADDRESS
     *
     * @return the value of V_HIS_PHYSICAL_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.MAILING_ADDRESS
     *
     * @param mailingAddress the value for V_HIS_PHYSICAL_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    public void setMailingAddress(String mailingAddress) {
        this.mailingAddress = mailingAddress == null ? null : mailingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.ZIP_CODE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.ZIP_CODE
     *
     * @param zipCode the value for V_HIS_PHYSICAL_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN
     *
     * @return the value of V_HIS_PHYSICAL_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    public String getNextOfKin() {
        return nextOfKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN
     *
     * @param nextOfKin the value for V_HIS_PHYSICAL_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    public void setNextOfKin(String nextOfKin) {
        this.nextOfKin = nextOfKin == null ? null : nextOfKin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.RELATIONSHIP_NAME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    public String getRelationshipName() {
        return relationshipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.RELATIONSHIP_NAME
     *
     * @param relationshipName the value for V_HIS_PHYSICAL_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    public void setRelationshipName(String relationshipName) {
        this.relationshipName = relationshipName == null ? null : relationshipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_ADDR
     *
     * @return the value of V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    public String getNextOfKinAddr() {
        return nextOfKinAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_ADDR
     *
     * @param nextOfKinAddr the value for V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    public void setNextOfKinAddr(String nextOfKinAddr) {
        this.nextOfKinAddr = nextOfKinAddr == null ? null : nextOfKinAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_PHONE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    public String getNextOfKinPhone() {
        return nextOfKinPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_PHONE
     *
     * @param nextOfKinPhone the value for V_HIS_PHYSICAL_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    public void setNextOfKinPhone(String nextOfKinPhone) {
        this.nextOfKinPhone = nextOfKinPhone == null ? null : nextOfKinPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.VIP_INDICATOR
     *
     * @return the value of V_HIS_PHYSICAL_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    public String getVipIndicator() {
        return vipIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.VIP_INDICATOR
     *
     * @param vipIndicator the value for V_HIS_PHYSICAL_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    public void setVipIndicator(String vipIndicator) {
        this.vipIndicator = vipIndicator == null ? null : vipIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PHYSICAL_TIME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PHYSICAL_TIME
     *
     * @mbggenerated
     */
    public Date getPhysicalTime() {
        return physicalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PHYSICAL_TIME
     *
     * @param physicalTime the value for V_HIS_PHYSICAL_INFO.PHYSICAL_TIME
     *
     * @mbggenerated
     */
    public void setPhysicalTime(Date physicalTime) {
        this.physicalTime = physicalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_CODE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getTotalInspectionDoctorCode() {
        return totalInspectionDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_CODE
     *
     * @param totalInspectionDoctorCode the value for V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setTotalInspectionDoctorCode(String totalInspectionDoctorCode) {
        this.totalInspectionDoctorCode = totalInspectionDoctorCode == null ? null : totalInspectionDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_NAME
     *
     * @return the value of V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getTotalInspectionDoctorName() {
        return totalInspectionDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_NAME
     *
     * @param totalInspectionDoctorName the value for V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setTotalInspectionDoctorName(String totalInspectionDoctorName) {
        this.totalInspectionDoctorName = totalInspectionDoctorName == null ? null : totalInspectionDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DATE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DATE
     *
     * @mbggenerated
     */
    public Date getTotalInspectionDate() {
        return totalInspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DATE
     *
     * @param totalInspectionDate the value for V_HIS_PHYSICAL_INFO.TOTAL_INSPECTION_DATE
     *
     * @mbggenerated
     */
    public void setTotalInspectionDate(Date totalInspectionDate) {
        this.totalInspectionDate = totalInspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.MARITAL_STATUS
     *
     * @return the value of V_HIS_PHYSICAL_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.MARITAL_STATUS
     *
     * @param maritalStatus the value for V_HIS_PHYSICAL_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.INSURANCE_TYPE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    public String getInsuranceType() {
        return insuranceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.INSURANCE_TYPE
     *
     * @param insuranceType the value for V_HIS_PHYSICAL_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType == null ? null : insuranceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @return the value of V_HIS_PHYSICAL_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    public String getMedicalInsuranceCardNo() {
        return medicalInsuranceCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @param medicalInsuranceCardNo the value for V_HIS_PHYSICAL_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    public void setMedicalInsuranceCardNo(String medicalInsuranceCardNo) {
        this.medicalInsuranceCardNo = medicalInsuranceCardNo == null ? null : medicalInsuranceCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @return the value of V_HIS_PHYSICAL_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    public String getSocialSecurityCardNo() {
        return socialSecurityCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @param socialSecurityCardNo the value for V_HIS_PHYSICAL_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    public void setSocialSecurityCardNo(String socialSecurityCardNo) {
        this.socialSecurityCardNo = socialSecurityCardNo == null ? null : socialSecurityCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PASSPORT_NO
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    public String getPassportNo() {
        return passportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PASSPORT_NO
     *
     * @param passportNo the value for V_HIS_PHYSICAL_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo == null ? null : passportNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.BLOOD_TYPE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.BLOOD_TYPE
     *
     * @param bloodType the value for V_HIS_PHYSICAL_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.RH_BLOOD_TYPE
     *
     * @return the value of V_HIS_PHYSICAL_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    public String getRhBloodType() {
        return rhBloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.RH_BLOOD_TYPE
     *
     * @param rhBloodType the value for V_HIS_PHYSICAL_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    public void setRhBloodType(String rhBloodType) {
        this.rhBloodType = rhBloodType == null ? null : rhBloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.WORK_UNIT
     *
     * @return the value of V_HIS_PHYSICAL_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.WORK_UNIT
     *
     * @param workUnit the value for V_HIS_PHYSICAL_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit == null ? null : workUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.PHONE_NUMBER
     *
     * @return the value of V_HIS_PHYSICAL_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for V_HIS_PHYSICAL_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.OVERVIEW
     *
     * @return the value of V_HIS_PHYSICAL_INFO.OVERVIEW
     *
     * @mbggenerated
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.OVERVIEW
     *
     * @param overview the value for V_HIS_PHYSICAL_INFO.OVERVIEW
     *
     * @mbggenerated
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_INFO.SUGGEST
     *
     * @return the value of V_HIS_PHYSICAL_INFO.SUGGEST
     *
     * @mbggenerated
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_INFO.SUGGEST
     *
     * @param suggest the value for V_HIS_PHYSICAL_INFO.SUGGEST
     *
     * @mbggenerated
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest == null ? null : suggest.trim();
    }
}