package com.kyee.model;

import java.util.Date;

public class VHisExamResultInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    private String examNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    private String examSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    private String examPara;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.IS_ABNORMAL
     *
     * @mbggenerated
     */
    private String isAbnormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    private Date resultDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String examDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String examDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String reviewDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String reviewDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    private String clinDiag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    private String insDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    private String insDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    private Date examDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    private String impression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    private String recommendation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_EXAM_RESULT_INFO.EXAM_TIPS
     *
     * @mbggenerated
     */
    private String examTips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_NO
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    public String getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_NO
     *
     * @param examNo the value for V_HIS_EXAM_RESULT_INFO.EXAM_NO
     *
     * @mbggenerated
     */
    public void setExamNo(String examNo) {
        this.examNo = examNo == null ? null : examNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_SOURCE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    public String getExamSource() {
        return examSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_SOURCE
     *
     * @param examSource the value for V_HIS_EXAM_RESULT_INFO.EXAM_SOURCE
     *
     * @mbggenerated
     */
    public void setExamSource(String examSource) {
        this.examSource = examSource == null ? null : examSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.ITEM_CODE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.ITEM_CODE
     *
     * @param itemCode the value for V_HIS_EXAM_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.ITEM_NAME
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.ITEM_NAME
     *
     * @param itemName the value for V_HIS_EXAM_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_PARA
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    public String getExamPara() {
        return examPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_PARA
     *
     * @param examPara the value for V_HIS_EXAM_RESULT_INFO.EXAM_PARA
     *
     * @mbggenerated
     */
    public void setExamPara(String examPara) {
        this.examPara = examPara == null ? null : examPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.IS_ABNORMAL
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.IS_ABNORMAL
     *
     * @mbggenerated
     */
    public String getIsAbnormal() {
        return isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.IS_ABNORMAL
     *
     * @param isAbnormal the value for V_HIS_EXAM_RESULT_INFO.IS_ABNORMAL
     *
     * @mbggenerated
     */
    public void setIsAbnormal(String isAbnormal) {
        this.isAbnormal = isAbnormal == null ? null : isAbnormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.RESULT_DATE_TIME
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getResultDateTime() {
        return resultDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.RESULT_DATE_TIME
     *
     * @param resultDateTime the value for V_HIS_EXAM_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    public void setResultDateTime(Date resultDateTime) {
        this.resultDateTime = resultDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_CODE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getExamDoctorCode() {
        return examDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_CODE
     *
     * @param examDoctorCode the value for V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setExamDoctorCode(String examDoctorCode) {
        this.examDoctorCode = examDoctorCode == null ? null : examDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_NAME
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getExamDoctorName() {
        return examDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_NAME
     *
     * @param examDoctorName the value for V_HIS_EXAM_RESULT_INFO.EXAM_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setExamDoctorName(String examDoctorName) {
        this.examDoctorName = examDoctorName == null ? null : examDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getReviewDoctorCode() {
        return reviewDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @param reviewDoctorCode the value for V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setReviewDoctorCode(String reviewDoctorCode) {
        this.reviewDoctorCode = reviewDoctorCode == null ? null : reviewDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getReviewDoctorName() {
        return reviewDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @param reviewDoctorName the value for V_HIS_EXAM_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setReviewDoctorName(String reviewDoctorName) {
        this.reviewDoctorName = reviewDoctorName == null ? null : reviewDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.CLIN_DIAG
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    public String getClinDiag() {
        return clinDiag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.CLIN_DIAG
     *
     * @param clinDiag the value for V_HIS_EXAM_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    public void setClinDiag(String clinDiag) {
        this.clinDiag = clinDiag == null ? null : clinDiag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_CODE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getInsDeptCode() {
        return insDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_CODE
     *
     * @param insDeptCode the value for V_HIS_EXAM_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setInsDeptCode(String insDeptCode) {
        this.insDeptCode = insDeptCode == null ? null : insDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_NAME
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public String getInsDeptName() {
        return insDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.INS_DEPT_NAME
     *
     * @param insDeptName the value for V_HIS_EXAM_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public void setInsDeptName(String insDeptName) {
        this.insDeptName = insDeptName == null ? null : insDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DATE
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_DATE
     *
     * @param examDate the value for V_HIS_EXAM_RESULT_INFO.EXAM_DATE
     *
     * @mbggenerated
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.DESCRIPTION
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.DESCRIPTION
     *
     * @param description the value for V_HIS_EXAM_RESULT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.IMPRESSION
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    public String getImpression() {
        return impression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.IMPRESSION
     *
     * @param impression the value for V_HIS_EXAM_RESULT_INFO.IMPRESSION
     *
     * @mbggenerated
     */
    public void setImpression(String impression) {
        this.impression = impression == null ? null : impression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.RECOMMENDATION
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    public String getRecommendation() {
        return recommendation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.RECOMMENDATION
     *
     * @param recommendation the value for V_HIS_EXAM_RESULT_INFO.RECOMMENDATION
     *
     * @mbggenerated
     */
    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation == null ? null : recommendation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_TIPS
     *
     * @return the value of V_HIS_EXAM_RESULT_INFO.EXAM_TIPS
     *
     * @mbggenerated
     */
    public String getExamTips() {
        return examTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_EXAM_RESULT_INFO.EXAM_TIPS
     *
     * @param examTips the value for V_HIS_EXAM_RESULT_INFO.EXAM_TIPS
     *
     * @mbggenerated
     */
    public void setExamTips(String examTips) {
        this.examTips = examTips == null ? null : examTips.trim();
    }
}