package com.kyee.model;

public class VHisDeptInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.CLINIC_ATTR
     *
     * @mbggenerated
     */
    private String clinicAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.OUTP_OR_INP
     *
     * @mbggenerated
     */
    private String outpOrInp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.INTERNAL_OR_SERGERY
     *
     * @mbggenerated
     */
    private String internalOrSergery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_DEPT_INFO.INPUT_CODE
     *
     * @mbggenerated
     */
    private String inputCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.DEPT_CODE
     *
     * @return the value of V_HIS_DEPT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.DEPT_CODE
     *
     * @param deptCode the value for V_HIS_DEPT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.DEPT_NAME
     *
     * @return the value of V_HIS_DEPT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.DEPT_NAME
     *
     * @param deptName the value for V_HIS_DEPT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.CLINIC_ATTR
     *
     * @return the value of V_HIS_DEPT_INFO.CLINIC_ATTR
     *
     * @mbggenerated
     */
    public String getClinicAttr() {
        return clinicAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.CLINIC_ATTR
     *
     * @param clinicAttr the value for V_HIS_DEPT_INFO.CLINIC_ATTR
     *
     * @mbggenerated
     */
    public void setClinicAttr(String clinicAttr) {
        this.clinicAttr = clinicAttr == null ? null : clinicAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.OUTP_OR_INP
     *
     * @return the value of V_HIS_DEPT_INFO.OUTP_OR_INP
     *
     * @mbggenerated
     */
    public String getOutpOrInp() {
        return outpOrInp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.OUTP_OR_INP
     *
     * @param outpOrInp the value for V_HIS_DEPT_INFO.OUTP_OR_INP
     *
     * @mbggenerated
     */
    public void setOutpOrInp(String outpOrInp) {
        this.outpOrInp = outpOrInp == null ? null : outpOrInp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.INTERNAL_OR_SERGERY
     *
     * @return the value of V_HIS_DEPT_INFO.INTERNAL_OR_SERGERY
     *
     * @mbggenerated
     */
    public String getInternalOrSergery() {
        return internalOrSergery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.INTERNAL_OR_SERGERY
     *
     * @param internalOrSergery the value for V_HIS_DEPT_INFO.INTERNAL_OR_SERGERY
     *
     * @mbggenerated
     */
    public void setInternalOrSergery(String internalOrSergery) {
        this.internalOrSergery = internalOrSergery == null ? null : internalOrSergery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_DEPT_INFO.INPUT_CODE
     *
     * @return the value of V_HIS_DEPT_INFO.INPUT_CODE
     *
     * @mbggenerated
     */
    public String getInputCode() {
        return inputCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_DEPT_INFO.INPUT_CODE
     *
     * @param inputCode the value for V_HIS_DEPT_INFO.INPUT_CODE
     *
     * @mbggenerated
     */
    public void setInputCode(String inputCode) {
        this.inputCode = inputCode == null ? null : inputCode.trim();
    }
}