package com.kyee.model;

import java.util.Date;

public class VHisClinicPatientInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    private String outpatientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.NATION
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    private String identityStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    private String mailingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    private String nextOfKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    private String relationshipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    private String nextOfKinAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    private String nextOfKinPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.OCCUPATION
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    private String insuranceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_NO
     *
     * @mbggenerated
     */
    private String insuranceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.VISITED_DATE_TIME
     *
     * @mbggenerated
     */
    private Date visitedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    private String diagnosisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    private String diagnosisName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    private String chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    private String vipIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    private String medicalInsuranceCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    private String socialSecurityCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    private String passportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    private String rhBloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    private String workUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_CLINIC_PATIENT_INFO.PAT_CONDITION_NAME
     *
     * @mbggenerated
     */
    private String patConditionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_ID
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_ID
     *
     * @param patientId the value for V_HIS_CLINIC_PATIENT_INFO.PATIENT_ID
     *
     * @mbggenerated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.OUTPATIENT_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public String getOutpatientNo() {
        return outpatientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.OUTPATIENT_NO
     *
     * @param outpatientNo the value for V_HIS_CLINIC_PATIENT_INFO.OUTPATIENT_NO
     *
     * @mbggenerated
     */
    public void setOutpatientNo(String outpatientNo) {
        this.outpatientNo = outpatientNo == null ? null : outpatientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_CODE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_CODE
     *
     * @param deptCode the value for V_HIS_CLINIC_PATIENT_INFO.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DEPT_NAME
     *
     * @param deptName the value for V_HIS_CLINIC_PATIENT_INFO.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.PATIENT_NAME
     *
     * @param patientName the value for V_HIS_CLINIC_PATIENT_INFO.PATIENT_NAME
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.SEX
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.SEX
     *
     * @param sex the value for V_HIS_CLINIC_PATIENT_INFO.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DATE_OF_BIRTH
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for V_HIS_CLINIC_PATIENT_INFO.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.AREA_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.AREA_NAME
     *
     * @param areaName the value for V_HIS_CLINIC_PATIENT_INFO.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.COUNTRY_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.COUNTRY_NAME
     *
     * @param countryName the value for V_HIS_CLINIC_PATIENT_INFO.COUNTRY_NAME
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.NATION
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.NATION
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.NATION
     *
     * @param nation the value for V_HIS_CLINIC_PATIENT_INFO.NATION
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.ID_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.ID_NO
     *
     * @param idNo the value for V_HIS_CLINIC_PATIENT_INFO.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.IDENTITY_STR
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    public String getIdentityStr() {
        return identityStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.IDENTITY_STR
     *
     * @param identityStr the value for V_HIS_CLINIC_PATIENT_INFO.IDENTITY_STR
     *
     * @mbggenerated
     */
    public void setIdentityStr(String identityStr) {
        this.identityStr = identityStr == null ? null : identityStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.MAILING_ADDRESS
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.MAILING_ADDRESS
     *
     * @param mailingAddress the value for V_HIS_CLINIC_PATIENT_INFO.MAILING_ADDRESS
     *
     * @mbggenerated
     */
    public void setMailingAddress(String mailingAddress) {
        this.mailingAddress = mailingAddress == null ? null : mailingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.ZIP_CODE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.ZIP_CODE
     *
     * @param zipCode the value for V_HIS_CLINIC_PATIENT_INFO.ZIP_CODE
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    public String getNextOfKin() {
        return nextOfKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN
     *
     * @param nextOfKin the value for V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN
     *
     * @mbggenerated
     */
    public void setNextOfKin(String nextOfKin) {
        this.nextOfKin = nextOfKin == null ? null : nextOfKin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.RELATIONSHIP_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    public String getRelationshipName() {
        return relationshipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.RELATIONSHIP_NAME
     *
     * @param relationshipName the value for V_HIS_CLINIC_PATIENT_INFO.RELATIONSHIP_NAME
     *
     * @mbggenerated
     */
    public void setRelationshipName(String relationshipName) {
        this.relationshipName = relationshipName == null ? null : relationshipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_ADDR
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    public String getNextOfKinAddr() {
        return nextOfKinAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_ADDR
     *
     * @param nextOfKinAddr the value for V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_ADDR
     *
     * @mbggenerated
     */
    public void setNextOfKinAddr(String nextOfKinAddr) {
        this.nextOfKinAddr = nextOfKinAddr == null ? null : nextOfKinAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_PHONE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    public String getNextOfKinPhone() {
        return nextOfKinPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_PHONE
     *
     * @param nextOfKinPhone the value for V_HIS_CLINIC_PATIENT_INFO.NEXT_OF_KIN_PHONE
     *
     * @mbggenerated
     */
    public void setNextOfKinPhone(String nextOfKinPhone) {
        this.nextOfKinPhone = nextOfKinPhone == null ? null : nextOfKinPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.OCCUPATION
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.OCCUPATION
     *
     * @mbggenerated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.OCCUPATION
     *
     * @param occupation the value for V_HIS_CLINIC_PATIENT_INFO.OCCUPATION
     *
     * @mbggenerated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.MARITAL_STATUS
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.MARITAL_STATUS
     *
     * @param maritalStatus the value for V_HIS_CLINIC_PATIENT_INFO.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_TYPE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    public String getInsuranceType() {
        return insuranceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_TYPE
     *
     * @param insuranceType the value for V_HIS_CLINIC_PATIENT_INFO.INSURANCE_TYPE
     *
     * @mbggenerated
     */
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType == null ? null : insuranceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.INSURANCE_NO
     *
     * @mbggenerated
     */
    public String getInsuranceNo() {
        return insuranceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.INSURANCE_NO
     *
     * @param insuranceNo the value for V_HIS_CLINIC_PATIENT_INFO.INSURANCE_NO
     *
     * @mbggenerated
     */
    public void setInsuranceNo(String insuranceNo) {
        this.insuranceNo = insuranceNo == null ? null : insuranceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.VISITED_DATE_TIME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.VISITED_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getVisitedDateTime() {
        return visitedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.VISITED_DATE_TIME
     *
     * @param visitedDateTime the value for V_HIS_CLINIC_PATIENT_INFO.VISITED_DATE_TIME
     *
     * @mbggenerated
     */
    public void setVisitedDateTime(Date visitedDateTime) {
        this.visitedDateTime = visitedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_CODE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public String getDiagnosisCode() {
        return diagnosisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_CODE
     *
     * @param diagnosisCode the value for V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_CODE
     *
     * @mbggenerated
     */
    public void setDiagnosisCode(String diagnosisCode) {
        this.diagnosisCode = diagnosisCode == null ? null : diagnosisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    public String getDiagnosisName() {
        return diagnosisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_NAME
     *
     * @param diagnosisName the value for V_HIS_CLINIC_PATIENT_INFO.DIAGNOSIS_NAME
     *
     * @mbggenerated
     */
    public void setDiagnosisName(String diagnosisName) {
        this.diagnosisName = diagnosisName == null ? null : diagnosisName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_NAME
     *
     * @param doctorName the value for V_HIS_CLINIC_PATIENT_INFO.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_CODE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.DOCTOR_CODE
     *
     * @param doctorCode the value for V_HIS_CLINIC_PATIENT_INFO.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.CHARGE_TYPE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.CHARGE_TYPE
     *
     * @param chargeType the value for V_HIS_CLINIC_PATIENT_INFO.CHARGE_TYPE
     *
     * @mbggenerated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.VIP_INDICATOR
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    public String getVipIndicator() {
        return vipIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.VIP_INDICATOR
     *
     * @param vipIndicator the value for V_HIS_CLINIC_PATIENT_INFO.VIP_INDICATOR
     *
     * @mbggenerated
     */
    public void setVipIndicator(String vipIndicator) {
        this.vipIndicator = vipIndicator == null ? null : vipIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    public String getMedicalInsuranceCardNo() {
        return medicalInsuranceCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @param medicalInsuranceCardNo the value for V_HIS_CLINIC_PATIENT_INFO.MEDICAL_INSURANCE_CARD_NO
     *
     * @mbggenerated
     */
    public void setMedicalInsuranceCardNo(String medicalInsuranceCardNo) {
        this.medicalInsuranceCardNo = medicalInsuranceCardNo == null ? null : medicalInsuranceCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    public String getSocialSecurityCardNo() {
        return socialSecurityCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @param socialSecurityCardNo the value for V_HIS_CLINIC_PATIENT_INFO.SOCIAL_SECURITY_CARD_NO
     *
     * @mbggenerated
     */
    public void setSocialSecurityCardNo(String socialSecurityCardNo) {
        this.socialSecurityCardNo = socialSecurityCardNo == null ? null : socialSecurityCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.PASSPORT_NO
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    public String getPassportNo() {
        return passportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.PASSPORT_NO
     *
     * @param passportNo the value for V_HIS_CLINIC_PATIENT_INFO.PASSPORT_NO
     *
     * @mbggenerated
     */
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo == null ? null : passportNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.BLOOD_TYPE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.BLOOD_TYPE
     *
     * @param bloodType the value for V_HIS_CLINIC_PATIENT_INFO.BLOOD_TYPE
     *
     * @mbggenerated
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.RH_BLOOD_TYPE
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    public String getRhBloodType() {
        return rhBloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.RH_BLOOD_TYPE
     *
     * @param rhBloodType the value for V_HIS_CLINIC_PATIENT_INFO.RH_BLOOD_TYPE
     *
     * @mbggenerated
     */
    public void setRhBloodType(String rhBloodType) {
        this.rhBloodType = rhBloodType == null ? null : rhBloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.WORK_UNIT
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.WORK_UNIT
     *
     * @param workUnit the value for V_HIS_CLINIC_PATIENT_INFO.WORK_UNIT
     *
     * @mbggenerated
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit == null ? null : workUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.PHONE_NUMBER
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for V_HIS_CLINIC_PATIENT_INFO.PHONE_NUMBER
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.E_MAIL
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.E_MAIL
     *
     * @param eMail the value for V_HIS_CLINIC_PATIENT_INFO.E_MAIL
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_CLINIC_PATIENT_INFO.PAT_CONDITION_NAME
     *
     * @return the value of V_HIS_CLINIC_PATIENT_INFO.PAT_CONDITION_NAME
     *
     * @mbggenerated
     */
    public String getPatConditionName() {
        return patConditionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_CLINIC_PATIENT_INFO.PAT_CONDITION_NAME
     *
     * @param patConditionName the value for V_HIS_CLINIC_PATIENT_INFO.PAT_CONDITION_NAME
     *
     * @mbggenerated
     */
    public void setPatConditionName(String patConditionName) {
        this.patConditionName = patConditionName == null ? null : patConditionName.trim();
    }
}