package com.kyee.model;

public class VHisUserDeptRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USER_DEPT_REL.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USER_DEPT_REL.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_USER_DEPT_REL.IS_ENABLE
     *
     * @mbggenerated
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USER_DEPT_REL.USER_ID
     *
     * @return the value of V_HIS_USER_DEPT_REL.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USER_DEPT_REL.USER_ID
     *
     * @param userId the value for V_HIS_USER_DEPT_REL.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USER_DEPT_REL.DEPT_CODE
     *
     * @return the value of V_HIS_USER_DEPT_REL.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USER_DEPT_REL.DEPT_CODE
     *
     * @param deptCode the value for V_HIS_USER_DEPT_REL.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_USER_DEPT_REL.IS_ENABLE
     *
     * @return the value of V_HIS_USER_DEPT_REL.IS_ENABLE
     *
     * @mbggenerated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_USER_DEPT_REL.IS_ENABLE
     *
     * @param isEnable the value for V_HIS_USER_DEPT_REL.IS_ENABLE
     *
     * @mbggenerated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }
}