package com.kyee.model;

import java.util.Date;

public class VHisLabResultInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.TEST_NO
     *
     * @mbggenerated
     */
    private String testNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.LAB_SOURCE
     *
     * @mbggenerated
     */
    private String labSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.RESULT
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.ABNORMAL_INDICATOR
     *
     * @mbggenerated
     */
    private String abnormalIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.UNITS
     *
     * @mbggenerated
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    private String referenceRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    private Date resultDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.LAB_DATE
     *
     * @mbggenerated
     */
    private Date labDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.SPECIMEN
     *
     * @mbggenerated
     */
    private String specimen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.NOTES_FOR_SPCM
     *
     * @mbggenerated
     */
    private String notesForSpcm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.SPCM_SAMPLE_DATE_TIME
     *
     * @mbggenerated
     */
    private Date spcmSampleDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.SPCM_RECEIVED_DATE_TIME
     *
     * @mbggenerated
     */
    private Date spcmReceivedDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    private String insDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    private String insDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    private String clinDiag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String labDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String labDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String reviewDoctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String reviewDoctorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.TEST_NO
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.TEST_NO
     *
     * @mbggenerated
     */
    public String getTestNo() {
        return testNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.TEST_NO
     *
     * @param testNo the value for V_HIS_LAB_RESULT_INFO.TEST_NO
     *
     * @mbggenerated
     */
    public void setTestNo(String testNo) {
        this.testNo = testNo == null ? null : testNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.LAB_SOURCE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.LAB_SOURCE
     *
     * @mbggenerated
     */
    public String getLabSource() {
        return labSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.LAB_SOURCE
     *
     * @param labSource the value for V_HIS_LAB_RESULT_INFO.LAB_SOURCE
     *
     * @mbggenerated
     */
    public void setLabSource(String labSource) {
        this.labSource = labSource == null ? null : labSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.ITEM_CODE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.ITEM_CODE
     *
     * @param itemCode the value for V_HIS_LAB_RESULT_INFO.ITEM_CODE
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.ITEM_NAME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.ITEM_NAME
     *
     * @param itemName the value for V_HIS_LAB_RESULT_INFO.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.RESULT
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.RESULT
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.RESULT
     *
     * @param result the value for V_HIS_LAB_RESULT_INFO.RESULT
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.ABNORMAL_INDICATOR
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.ABNORMAL_INDICATOR
     *
     * @mbggenerated
     */
    public String getAbnormalIndicator() {
        return abnormalIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.ABNORMAL_INDICATOR
     *
     * @param abnormalIndicator the value for V_HIS_LAB_RESULT_INFO.ABNORMAL_INDICATOR
     *
     * @mbggenerated
     */
    public void setAbnormalIndicator(String abnormalIndicator) {
        this.abnormalIndicator = abnormalIndicator == null ? null : abnormalIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.UNITS
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.UNITS
     *
     * @mbggenerated
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.UNITS
     *
     * @param units the value for V_HIS_LAB_RESULT_INFO.UNITS
     *
     * @mbggenerated
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.REFERENCE_RANGE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    public String getReferenceRange() {
        return referenceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.REFERENCE_RANGE
     *
     * @param referenceRange the value for V_HIS_LAB_RESULT_INFO.REFERENCE_RANGE
     *
     * @mbggenerated
     */
    public void setReferenceRange(String referenceRange) {
        this.referenceRange = referenceRange == null ? null : referenceRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.RESULT_DATE_TIME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getResultDateTime() {
        return resultDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.RESULT_DATE_TIME
     *
     * @param resultDateTime the value for V_HIS_LAB_RESULT_INFO.RESULT_DATE_TIME
     *
     * @mbggenerated
     */
    public void setResultDateTime(Date resultDateTime) {
        this.resultDateTime = resultDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DATE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.LAB_DATE
     *
     * @mbggenerated
     */
    public Date getLabDate() {
        return labDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DATE
     *
     * @param labDate the value for V_HIS_LAB_RESULT_INFO.LAB_DATE
     *
     * @mbggenerated
     */
    public void setLabDate(Date labDate) {
        this.labDate = labDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.SPECIMEN
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.SPECIMEN
     *
     * @mbggenerated
     */
    public String getSpecimen() {
        return specimen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.SPECIMEN
     *
     * @param specimen the value for V_HIS_LAB_RESULT_INFO.SPECIMEN
     *
     * @mbggenerated
     */
    public void setSpecimen(String specimen) {
        this.specimen = specimen == null ? null : specimen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.NOTES_FOR_SPCM
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.NOTES_FOR_SPCM
     *
     * @mbggenerated
     */
    public String getNotesForSpcm() {
        return notesForSpcm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.NOTES_FOR_SPCM
     *
     * @param notesForSpcm the value for V_HIS_LAB_RESULT_INFO.NOTES_FOR_SPCM
     *
     * @mbggenerated
     */
    public void setNotesForSpcm(String notesForSpcm) {
        this.notesForSpcm = notesForSpcm == null ? null : notesForSpcm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.SPCM_SAMPLE_DATE_TIME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.SPCM_SAMPLE_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getSpcmSampleDateTime() {
        return spcmSampleDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.SPCM_SAMPLE_DATE_TIME
     *
     * @param spcmSampleDateTime the value for V_HIS_LAB_RESULT_INFO.SPCM_SAMPLE_DATE_TIME
     *
     * @mbggenerated
     */
    public void setSpcmSampleDateTime(Date spcmSampleDateTime) {
        this.spcmSampleDateTime = spcmSampleDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.SPCM_RECEIVED_DATE_TIME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.SPCM_RECEIVED_DATE_TIME
     *
     * @mbggenerated
     */
    public Date getSpcmReceivedDateTime() {
        return spcmReceivedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.SPCM_RECEIVED_DATE_TIME
     *
     * @param spcmReceivedDateTime the value for V_HIS_LAB_RESULT_INFO.SPCM_RECEIVED_DATE_TIME
     *
     * @mbggenerated
     */
    public void setSpcmReceivedDateTime(Date spcmReceivedDateTime) {
        this.spcmReceivedDateTime = spcmReceivedDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_CODE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getInsDeptCode() {
        return insDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_CODE
     *
     * @param insDeptCode the value for V_HIS_LAB_RESULT_INFO.INS_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setInsDeptCode(String insDeptCode) {
        this.insDeptCode = insDeptCode == null ? null : insDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_NAME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public String getInsDeptName() {
        return insDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.INS_DEPT_NAME
     *
     * @param insDeptName the value for V_HIS_LAB_RESULT_INFO.INS_DEPT_NAME
     *
     * @mbggenerated
     */
    public void setInsDeptName(String insDeptName) {
        this.insDeptName = insDeptName == null ? null : insDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.CLIN_DIAG
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    public String getClinDiag() {
        return clinDiag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.CLIN_DIAG
     *
     * @param clinDiag the value for V_HIS_LAB_RESULT_INFO.CLIN_DIAG
     *
     * @mbggenerated
     */
    public void setClinDiag(String clinDiag) {
        this.clinDiag = clinDiag == null ? null : clinDiag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_CODE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getLabDoctorCode() {
        return labDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_CODE
     *
     * @param labDoctorCode the value for V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setLabDoctorCode(String labDoctorCode) {
        this.labDoctorCode = labDoctorCode == null ? null : labDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_NAME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getLabDoctorName() {
        return labDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_NAME
     *
     * @param labDoctorName the value for V_HIS_LAB_RESULT_INFO.LAB_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setLabDoctorName(String labDoctorName) {
        this.labDoctorName = labDoctorName == null ? null : labDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getReviewDoctorCode() {
        return reviewDoctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @param reviewDoctorCode the value for V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setReviewDoctorCode(String reviewDoctorCode) {
        this.reviewDoctorCode = reviewDoctorCode == null ? null : reviewDoctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @return the value of V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getReviewDoctorName() {
        return reviewDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @param reviewDoctorName the value for V_HIS_LAB_RESULT_INFO.REVIEW_DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setReviewDoctorName(String reviewDoctorName) {
        this.reviewDoctorName = reviewDoctorName == null ? null : reviewDoctorName.trim();
    }
}