package com.kyee.model;

import java.util.Date;

public class VHisPhysicalSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    private String physicalSummaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    private String physicalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    private String itemClassCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    private String itemClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    private String physicalSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_CODE
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_NAME
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_TIME
     *
     * @mbggenerated
     */
    private Date physicalSummaryTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_ID
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    public String getPhysicalSummaryId() {
        return physicalSummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_ID
     *
     * @param physicalSummaryId the value for V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_ID
     *
     * @mbggenerated
     */
    public void setPhysicalSummaryId(String physicalSummaryId) {
        this.physicalSummaryId = physicalSummaryId == null ? null : physicalSummaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_NUMBER
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public String getPhysicalNumber() {
        return physicalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_NUMBER
     *
     * @param physicalNumber the value for V_HIS_PHYSICAL_SUMMARY.PHYSICAL_NUMBER
     *
     * @mbggenerated
     */
    public void setPhysicalNumber(String physicalNumber) {
        this.physicalNumber = physicalNumber == null ? null : physicalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_CODE
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    public String getItemClassCode() {
        return itemClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_CODE
     *
     * @param itemClassCode the value for V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_CODE
     *
     * @mbggenerated
     */
    public void setItemClassCode(String itemClassCode) {
        this.itemClassCode = itemClassCode == null ? null : itemClassCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_NAME
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    public String getItemClassName() {
        return itemClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_NAME
     *
     * @param itemClassName the value for V_HIS_PHYSICAL_SUMMARY.ITEM_CLASS_NAME
     *
     * @mbggenerated
     */
    public void setItemClassName(String itemClassName) {
        this.itemClassName = itemClassName == null ? null : itemClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    public String getPhysicalSummary() {
        return physicalSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY
     *
     * @param physicalSummary the value for V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY
     *
     * @mbggenerated
     */
    public void setPhysicalSummary(String physicalSummary) {
        this.physicalSummary = physicalSummary == null ? null : physicalSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_CODE
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_CODE
     *
     * @param doctorCode the value for V_HIS_PHYSICAL_SUMMARY.DOCTOR_CODE
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_NAME
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.DOCTOR_NAME
     *
     * @param doctorName the value for V_HIS_PHYSICAL_SUMMARY.DOCTOR_NAME
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_TIME
     *
     * @return the value of V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_TIME
     *
     * @mbggenerated
     */
    public Date getPhysicalSummaryTime() {
        return physicalSummaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_TIME
     *
     * @param physicalSummaryTime the value for V_HIS_PHYSICAL_SUMMARY.PHYSICAL_SUMMARY_TIME
     *
     * @mbggenerated
     */
    public void setPhysicalSummaryTime(Date physicalSummaryTime) {
        this.physicalSummaryTime = physicalSummaryTime;
    }
}